package pe.gob.miraflores.mobile.dao.detalleincidencia;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.detalleincidencia.GeoDetalleIncidencia;
import pe.gob.miraflores.mobile.domain.detalleincidencia.GeoDetalleIncidenciaCriteria;

public interface GeoDetalleIncidenciaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INFO_TETRA
	 * @mbggenerated  Wed Feb 03 16:58:21 COT 2016
	 */
	int countByExample(GeoDetalleIncidenciaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INFO_TETRA
	 * @mbggenerated  Wed Feb 03 16:58:21 COT 2016
	 */
	int deleteByExample(GeoDetalleIncidenciaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INFO_TETRA
	 * @mbggenerated  Wed Feb 03 16:58:21 COT 2016
	 */
	int deleteByPrimaryKey(Integer issi);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INFO_TETRA
	 * @mbggenerated  Wed Feb 03 16:58:21 COT 2016
	 */
	int insert(GeoDetalleIncidencia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INFO_TETRA
	 * @mbggenerated  Wed Feb 03 16:58:21 COT 2016
	 */
	int insertSelective(GeoDetalleIncidencia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INFO_TETRA
	 * @mbggenerated  Wed Feb 03 16:58:21 COT 2016
	 */
	List<GeoDetalleIncidencia> selectByExample(GeoDetalleIncidenciaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INFO_TETRA
	 * @mbggenerated  Wed Feb 03 16:58:21 COT 2016
	 */
	GeoDetalleIncidencia selectByPrimaryKey(Integer issi);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INFO_TETRA
	 * @mbggenerated  Wed Feb 03 16:58:21 COT 2016
	 */
	int updateByExampleSelective(@Param("record") GeoDetalleIncidencia record,
			@Param("example") GeoDetalleIncidenciaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INFO_TETRA
	 * @mbggenerated  Wed Feb 03 16:58:21 COT 2016
	 */
	int updateByExample(@Param("record") GeoDetalleIncidencia record,
			@Param("example") GeoDetalleIncidenciaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INFO_TETRA
	 * @mbggenerated  Wed Feb 03 16:58:21 COT 2016
	 */
	int updateByPrimaryKeySelective(GeoDetalleIncidencia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INFO_TETRA
	 * @mbggenerated  Wed Feb 03 16:58:21 COT 2016
	 */
	int updateByPrimaryKey(GeoDetalleIncidencia record);
}