package pe.gob.miraflores.mobile.dao.catalogo;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.catalogo.GrupoCatalogo;
import pe.gob.miraflores.mobile.domain.catalogo.GrupoCatalogoCriteria;

public interface GrupoCatalogoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CTLMGPOELE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	int countByExample(GrupoCatalogoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CTLMGPOELE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	int deleteByExample(GrupoCatalogoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CTLMGPOELE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	int deleteByPrimaryKey(Integer ideGrupoElemento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CTLMGPOELE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	int insert(GrupoCatalogo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CTLMGPOELE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	int insertSelective(GrupoCatalogo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CTLMGPOELE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	List<GrupoCatalogo> selectByExample(GrupoCatalogoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CTLMGPOELE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	GrupoCatalogo selectByPrimaryKey(Integer ideGrupoElemento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CTLMGPOELE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	int updateByExampleSelective(@Param("record") GrupoCatalogo record,
			@Param("example") GrupoCatalogoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CTLMGPOELE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	int updateByExample(@Param("record") GrupoCatalogo record, @Param("example") GrupoCatalogoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CTLMGPOELE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	int updateByPrimaryKeySelective(GrupoCatalogo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CTLMGPOELE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	int updateByPrimaryKey(GrupoCatalogo record);
}