package pe.gob.miraflores.mobile.domain.catalogo;

import java.util.Date;

public class GrupoCatalogo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CTLMGPOELE.IDE_GRUPO_ELEMENTO
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	private Integer ideGrupoElemento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CTLMGPOELE.IDE_GRUPO_ELEMENT1
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	private Integer ideGrupoElement1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CTLMGPOELE.DES_NOMBRE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	private String desNombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CTLMGPOELE.CLV_ABREVIAR_GRUPO
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	private String clvAbreviarGrupo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CTLMGPOELE.COD_ESTADO
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	private String codEstado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CTLMGPOELE.FEC_CREACION
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	private Date fecCreacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CTLMGPOELE.REF_1
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	private String ref1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CTLMGPOELE.REF_2
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	private String ref2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CTLMGPOELE.REF_3
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	private String ref3;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CTLMGPOELE.IDE_GRUPO_ELEMENTO
	 * @return  the value of CTLMGPOELE.IDE_GRUPO_ELEMENTO
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public Integer getIdeGrupoElemento() {
		return ideGrupoElemento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CTLMGPOELE.IDE_GRUPO_ELEMENTO
	 * @param ideGrupoElemento  the value for CTLMGPOELE.IDE_GRUPO_ELEMENTO
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public void setIdeGrupoElemento(Integer ideGrupoElemento) {
		this.ideGrupoElemento = ideGrupoElemento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CTLMGPOELE.IDE_GRUPO_ELEMENT1
	 * @return  the value of CTLMGPOELE.IDE_GRUPO_ELEMENT1
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public Integer getIdeGrupoElement1() {
		return ideGrupoElement1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CTLMGPOELE.IDE_GRUPO_ELEMENT1
	 * @param ideGrupoElement1  the value for CTLMGPOELE.IDE_GRUPO_ELEMENT1
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public void setIdeGrupoElement1(Integer ideGrupoElement1) {
		this.ideGrupoElement1 = ideGrupoElement1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CTLMGPOELE.DES_NOMBRE
	 * @return  the value of CTLMGPOELE.DES_NOMBRE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public String getDesNombre() {
		return desNombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CTLMGPOELE.DES_NOMBRE
	 * @param desNombre  the value for CTLMGPOELE.DES_NOMBRE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public void setDesNombre(String desNombre) {
		this.desNombre = desNombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CTLMGPOELE.CLV_ABREVIAR_GRUPO
	 * @return  the value of CTLMGPOELE.CLV_ABREVIAR_GRUPO
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public String getClvAbreviarGrupo() {
		return clvAbreviarGrupo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CTLMGPOELE.CLV_ABREVIAR_GRUPO
	 * @param clvAbreviarGrupo  the value for CTLMGPOELE.CLV_ABREVIAR_GRUPO
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public void setClvAbreviarGrupo(String clvAbreviarGrupo) {
		this.clvAbreviarGrupo = clvAbreviarGrupo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CTLMGPOELE.COD_ESTADO
	 * @return  the value of CTLMGPOELE.COD_ESTADO
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public String getCodEstado() {
		return codEstado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CTLMGPOELE.COD_ESTADO
	 * @param codEstado  the value for CTLMGPOELE.COD_ESTADO
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public void setCodEstado(String codEstado) {
		this.codEstado = codEstado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CTLMGPOELE.FEC_CREACION
	 * @return  the value of CTLMGPOELE.FEC_CREACION
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public Date getFecCreacion() {
		return fecCreacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CTLMGPOELE.FEC_CREACION
	 * @param fecCreacion  the value for CTLMGPOELE.FEC_CREACION
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CTLMGPOELE.REF_1
	 * @return  the value of CTLMGPOELE.REF_1
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public String getRef1() {
		return ref1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CTLMGPOELE.REF_1
	 * @param ref1  the value for CTLMGPOELE.REF_1
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public void setRef1(String ref1) {
		this.ref1 = ref1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CTLMGPOELE.REF_2
	 * @return  the value of CTLMGPOELE.REF_2
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public String getRef2() {
		return ref2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CTLMGPOELE.REF_2
	 * @param ref2  the value for CTLMGPOELE.REF_2
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public void setRef2(String ref2) {
		this.ref2 = ref2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CTLMGPOELE.REF_3
	 * @return  the value of CTLMGPOELE.REF_3
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public String getRef3() {
		return ref3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CTLMGPOELE.REF_3
	 * @param ref3  the value for CTLMGPOELE.REF_3
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	public void setRef3(String ref3) {
		this.ref3 = ref3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CTLMGPOELE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		GrupoCatalogo other = (GrupoCatalogo) that;
		return (this.getIdeGrupoElemento() == null ? other.getIdeGrupoElemento() == null
				: this.getIdeGrupoElemento().equals(other.getIdeGrupoElemento()))
				&& (this.getIdeGrupoElement1() == null ? other.getIdeGrupoElement1() == null
						: this.getIdeGrupoElement1().equals(other.getIdeGrupoElement1()))
				&& (this.getDesNombre() == null ? other.getDesNombre() == null
						: this.getDesNombre().equals(other.getDesNombre()))
				&& (this.getClvAbreviarGrupo() == null ? other.getClvAbreviarGrupo() == null
						: this.getClvAbreviarGrupo().equals(other.getClvAbreviarGrupo()))
				&& (this.getCodEstado() == null ? other.getCodEstado() == null
						: this.getCodEstado().equals(other.getCodEstado()))
				&& (this.getFecCreacion() == null ? other.getFecCreacion() == null
						: this.getFecCreacion().equals(other.getFecCreacion()))
				&& (this.getRef1() == null ? other.getRef1() == null : this.getRef1().equals(other.getRef1()))
				&& (this.getRef2() == null ? other.getRef2() == null : this.getRef2().equals(other.getRef2()))
				&& (this.getRef3() == null ? other.getRef3() == null : this.getRef3().equals(other.getRef3()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CTLMGPOELE
	 * @mbggenerated  Tue Jul 26 11:25:11 COT 2016
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getIdeGrupoElemento() == null) ? 0 : getIdeGrupoElemento().hashCode());
		result = prime * result + ((getIdeGrupoElement1() == null) ? 0 : getIdeGrupoElement1().hashCode());
		result = prime * result + ((getDesNombre() == null) ? 0 : getDesNombre().hashCode());
		result = prime * result + ((getClvAbreviarGrupo() == null) ? 0 : getClvAbreviarGrupo().hashCode());
		result = prime * result + ((getCodEstado() == null) ? 0 : getCodEstado().hashCode());
		result = prime * result + ((getFecCreacion() == null) ? 0 : getFecCreacion().hashCode());
		result = prime * result + ((getRef1() == null) ? 0 : getRef1().hashCode());
		result = prime * result + ((getRef2() == null) ? 0 : getRef2().hashCode());
		result = prime * result + ((getRef3() == null) ? 0 : getRef3().hashCode());
		return result;
	}
}