package pe.gob.miraflores.mobile.domain.mapaincidencias;

import java.util.Date;

public class AuditoriaIncidencia {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_MAP_AUDITORIA.ID
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_MAP_AUDITORIA.TIPO
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    private String tipo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_MAP_AUDITORIA.VALOR
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    private String valor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_MAP_AUDITORIA.FEC_REGISTRA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    private Date fecRegistra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GEO_MAP_AUDITORIA.DES_IP_REGISTRA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    private String desIpRegistra;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_MAP_AUDITORIA.ID
     *
     * @return the value of GEO_MAP_AUDITORIA.ID
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_MAP_AUDITORIA.ID
     *
     * @param id the value for GEO_MAP_AUDITORIA.ID
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_MAP_AUDITORIA.TIPO
     *
     * @return the value of GEO_MAP_AUDITORIA.TIPO
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_MAP_AUDITORIA.TIPO
     *
     * @param tipo the value for GEO_MAP_AUDITORIA.TIPO
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_MAP_AUDITORIA.VALOR
     *
     * @return the value of GEO_MAP_AUDITORIA.VALOR
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    public String getValor() {
        return valor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_MAP_AUDITORIA.VALOR
     *
     * @param valor the value for GEO_MAP_AUDITORIA.VALOR
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    public void setValor(String valor) {
        this.valor = valor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_MAP_AUDITORIA.FEC_REGISTRA
     *
     * @return the value of GEO_MAP_AUDITORIA.FEC_REGISTRA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    public Date getFecRegistra() {
        return fecRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_MAP_AUDITORIA.FEC_REGISTRA
     *
     * @param fecRegistra the value for GEO_MAP_AUDITORIA.FEC_REGISTRA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    public void setFecRegistra(Date fecRegistra) {
        this.fecRegistra = fecRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GEO_MAP_AUDITORIA.DES_IP_REGISTRA
     *
     * @return the value of GEO_MAP_AUDITORIA.DES_IP_REGISTRA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    public String getDesIpRegistra() {
        return desIpRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GEO_MAP_AUDITORIA.DES_IP_REGISTRA
     *
     * @param desIpRegistra the value for GEO_MAP_AUDITORIA.DES_IP_REGISTRA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    public void setDesIpRegistra(String desIpRegistra) {
        this.desIpRegistra = desIpRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_AUDITORIA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AuditoriaIncidencia other = (AuditoriaIncidencia) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTipo() == null ? other.getTipo() == null : this.getTipo().equals(other.getTipo()))
            && (this.getValor() == null ? other.getValor() == null : this.getValor().equals(other.getValor()))
            && (this.getFecRegistra() == null ? other.getFecRegistra() == null : this.getFecRegistra().equals(other.getFecRegistra()))
            && (this.getDesIpRegistra() == null ? other.getDesIpRegistra() == null : this.getDesIpRegistra().equals(other.getDesIpRegistra()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_AUDITORIA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTipo() == null) ? 0 : getTipo().hashCode());
        result = prime * result + ((getValor() == null) ? 0 : getValor().hashCode());
        result = prime * result + ((getFecRegistra() == null) ? 0 : getFecRegistra().hashCode());
        result = prime * result + ((getDesIpRegistra() == null) ? 0 : getDesIpRegistra().hashCode());
        return result;
    }
}