package pe.gob.miraflores.mobile.domain.mapaincidencias;

public class MapaIncidenciaGenerico {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.ID
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.GEOMETRIA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String geometria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.NOMBRE
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.NOMBRE_VIA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String nombreVia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.NUMERO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String numero;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.LETRA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String letra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.INTERIOR
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String interior;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.GIRO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String giro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.PUBLICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String publico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.ZONA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String zona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.TIPO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private Integer tipo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.PUNTO_INI
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String puntoIni;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.PUNTO_FIN
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String puntoFin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.TRAMO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String tramo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.VIA_INI
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String viaIni;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.VIA_FIN
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String viaFin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.SENTIDO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String sentido;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.PERCENTIL
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String percentil;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.LIMITE
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String limite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.ESPACIOS
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String espacios;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.SECTOR
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String sector;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.CUADRA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String cuadra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.LADO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String lado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.HORA_PASO_PROMEDIO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String horaPasoPromedio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_MAP_GENERICO.DETALLE
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	private String detalle;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.ID
	 * @return  the value of GEO_MAP_GENERICO.ID
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.ID
	 * @param id  the value for GEO_MAP_GENERICO.ID
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.GEOMETRIA
	 * @return  the value of GEO_MAP_GENERICO.GEOMETRIA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getGeometria() {
		return geometria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.GEOMETRIA
	 * @param geometria  the value for GEO_MAP_GENERICO.GEOMETRIA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setGeometria(String geometria) {
		this.geometria = geometria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.NOMBRE
	 * @return  the value of GEO_MAP_GENERICO.NOMBRE
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.NOMBRE
	 * @param nombre  the value for GEO_MAP_GENERICO.NOMBRE
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.NOMBRE_VIA
	 * @return  the value of GEO_MAP_GENERICO.NOMBRE_VIA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getNombreVia() {
		return nombreVia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.NOMBRE_VIA
	 * @param nombreVia  the value for GEO_MAP_GENERICO.NOMBRE_VIA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setNombreVia(String nombreVia) {
		this.nombreVia = nombreVia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.NUMERO
	 * @return  the value of GEO_MAP_GENERICO.NUMERO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getNumero() {
		return numero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.NUMERO
	 * @param numero  the value for GEO_MAP_GENERICO.NUMERO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setNumero(String numero) {
		this.numero = numero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.LETRA
	 * @return  the value of GEO_MAP_GENERICO.LETRA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getLetra() {
		return letra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.LETRA
	 * @param letra  the value for GEO_MAP_GENERICO.LETRA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setLetra(String letra) {
		this.letra = letra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.INTERIOR
	 * @return  the value of GEO_MAP_GENERICO.INTERIOR
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getInterior() {
		return interior;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.INTERIOR
	 * @param interior  the value for GEO_MAP_GENERICO.INTERIOR
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setInterior(String interior) {
		this.interior = interior;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.GIRO
	 * @return  the value of GEO_MAP_GENERICO.GIRO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getGiro() {
		return giro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.GIRO
	 * @param giro  the value for GEO_MAP_GENERICO.GIRO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setGiro(String giro) {
		this.giro = giro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.PUBLICO
	 * @return  the value of GEO_MAP_GENERICO.PUBLICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getPublico() {
		return publico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.PUBLICO
	 * @param publico  the value for GEO_MAP_GENERICO.PUBLICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setPublico(String publico) {
		this.publico = publico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.ZONA
	 * @return  the value of GEO_MAP_GENERICO.ZONA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getZona() {
		return zona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.ZONA
	 * @param zona  the value for GEO_MAP_GENERICO.ZONA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setZona(String zona) {
		this.zona = zona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.TIPO
	 * @return  the value of GEO_MAP_GENERICO.TIPO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public Integer getTipo() {
		return tipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.TIPO
	 * @param tipo  the value for GEO_MAP_GENERICO.TIPO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.PUNTO_INI
	 * @return  the value of GEO_MAP_GENERICO.PUNTO_INI
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getPuntoIni() {
		return puntoIni;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.PUNTO_INI
	 * @param puntoIni  the value for GEO_MAP_GENERICO.PUNTO_INI
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setPuntoIni(String puntoIni) {
		this.puntoIni = puntoIni;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.PUNTO_FIN
	 * @return  the value of GEO_MAP_GENERICO.PUNTO_FIN
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getPuntoFin() {
		return puntoFin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.PUNTO_FIN
	 * @param puntoFin  the value for GEO_MAP_GENERICO.PUNTO_FIN
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setPuntoFin(String puntoFin) {
		this.puntoFin = puntoFin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.TRAMO
	 * @return  the value of GEO_MAP_GENERICO.TRAMO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getTramo() {
		return tramo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.TRAMO
	 * @param tramo  the value for GEO_MAP_GENERICO.TRAMO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setTramo(String tramo) {
		this.tramo = tramo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.VIA_INI
	 * @return  the value of GEO_MAP_GENERICO.VIA_INI
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getViaIni() {
		return viaIni;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.VIA_INI
	 * @param viaIni  the value for GEO_MAP_GENERICO.VIA_INI
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setViaIni(String viaIni) {
		this.viaIni = viaIni;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.VIA_FIN
	 * @return  the value of GEO_MAP_GENERICO.VIA_FIN
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getViaFin() {
		return viaFin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.VIA_FIN
	 * @param viaFin  the value for GEO_MAP_GENERICO.VIA_FIN
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setViaFin(String viaFin) {
		this.viaFin = viaFin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.SENTIDO
	 * @return  the value of GEO_MAP_GENERICO.SENTIDO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getSentido() {
		return sentido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.SENTIDO
	 * @param sentido  the value for GEO_MAP_GENERICO.SENTIDO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setSentido(String sentido) {
		this.sentido = sentido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.PERCENTIL
	 * @return  the value of GEO_MAP_GENERICO.PERCENTIL
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getPercentil() {
		return percentil;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.PERCENTIL
	 * @param percentil  the value for GEO_MAP_GENERICO.PERCENTIL
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setPercentil(String percentil) {
		this.percentil = percentil;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.LIMITE
	 * @return  the value of GEO_MAP_GENERICO.LIMITE
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getLimite() {
		return limite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.LIMITE
	 * @param limite  the value for GEO_MAP_GENERICO.LIMITE
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setLimite(String limite) {
		this.limite = limite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.ESPACIOS
	 * @return  the value of GEO_MAP_GENERICO.ESPACIOS
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getEspacios() {
		return espacios;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.ESPACIOS
	 * @param espacios  the value for GEO_MAP_GENERICO.ESPACIOS
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setEspacios(String espacios) {
		this.espacios = espacios;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.SECTOR
	 * @return  the value of GEO_MAP_GENERICO.SECTOR
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getSector() {
		return sector;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.SECTOR
	 * @param sector  the value for GEO_MAP_GENERICO.SECTOR
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setSector(String sector) {
		this.sector = sector;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.CUADRA
	 * @return  the value of GEO_MAP_GENERICO.CUADRA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getCuadra() {
		return cuadra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.CUADRA
	 * @param cuadra  the value for GEO_MAP_GENERICO.CUADRA
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setCuadra(String cuadra) {
		this.cuadra = cuadra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.LADO
	 * @return  the value of GEO_MAP_GENERICO.LADO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getLado() {
		return lado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.LADO
	 * @param lado  the value for GEO_MAP_GENERICO.LADO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setLado(String lado) {
		this.lado = lado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.HORA_PASO_PROMEDIO
	 * @return  the value of GEO_MAP_GENERICO.HORA_PASO_PROMEDIO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getHoraPasoPromedio() {
		return horaPasoPromedio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.HORA_PASO_PROMEDIO
	 * @param horaPasoPromedio  the value for GEO_MAP_GENERICO.HORA_PASO_PROMEDIO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setHoraPasoPromedio(String horaPasoPromedio) {
		this.horaPasoPromedio = horaPasoPromedio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_MAP_GENERICO.DETALLE
	 * @return  the value of GEO_MAP_GENERICO.DETALLE
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getDetalle() {
		return detalle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_MAP_GENERICO.DETALLE
	 * @param detalle  the value for GEO_MAP_GENERICO.DETALLE
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		MapaIncidenciaGenerico other = (MapaIncidenciaGenerico) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getGeometria() == null ? other.getGeometria() == null
						: this.getGeometria().equals(other.getGeometria()))
				&& (this.getNombre() == null ? other.getNombre() == null : this.getNombre().equals(other.getNombre()))
				&& (this.getNombreVia() == null ? other.getNombreVia() == null
						: this.getNombreVia().equals(other.getNombreVia()))
				&& (this.getNumero() == null ? other.getNumero() == null : this.getNumero().equals(other.getNumero()))
				&& (this.getLetra() == null ? other.getLetra() == null : this.getLetra().equals(other.getLetra()))
				&& (this.getInterior() == null ? other.getInterior() == null
						: this.getInterior().equals(other.getInterior()))
				&& (this.getGiro() == null ? other.getGiro() == null : this.getGiro().equals(other.getGiro()))
				&& (this.getPublico() == null ? other.getPublico() == null
						: this.getPublico().equals(other.getPublico()))
				&& (this.getZona() == null ? other.getZona() == null : this.getZona().equals(other.getZona()))
				&& (this.getTipo() == null ? other.getTipo() == null : this.getTipo().equals(other.getTipo()))
				&& (this.getPuntoIni() == null ? other.getPuntoIni() == null
						: this.getPuntoIni().equals(other.getPuntoIni()))
				&& (this.getPuntoFin() == null ? other.getPuntoFin() == null
						: this.getPuntoFin().equals(other.getPuntoFin()))
				&& (this.getTramo() == null ? other.getTramo() == null : this.getTramo().equals(other.getTramo()))
				&& (this.getViaIni() == null ? other.getViaIni() == null : this.getViaIni().equals(other.getViaIni()))
				&& (this.getViaFin() == null ? other.getViaFin() == null : this.getViaFin().equals(other.getViaFin()))
				&& (this.getSentido() == null ? other.getSentido() == null
						: this.getSentido().equals(other.getSentido()))
				&& (this.getPercentil() == null ? other.getPercentil() == null
						: this.getPercentil().equals(other.getPercentil()))
				&& (this.getLimite() == null ? other.getLimite() == null : this.getLimite().equals(other.getLimite()))
				&& (this.getEspacios() == null ? other.getEspacios() == null
						: this.getEspacios().equals(other.getEspacios()))
				&& (this.getSector() == null ? other.getSector() == null : this.getSector().equals(other.getSector()))
				&& (this.getCuadra() == null ? other.getCuadra() == null : this.getCuadra().equals(other.getCuadra()))
				&& (this.getLado() == null ? other.getLado() == null : this.getLado().equals(other.getLado()))
				&& (this.getHoraPasoPromedio() == null ? other.getHoraPasoPromedio() == null
						: this.getHoraPasoPromedio().equals(other.getHoraPasoPromedio()))
				&& (this.getDetalle() == null ? other.getDetalle() == null
						: this.getDetalle().equals(other.getDetalle()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getGeometria() == null) ? 0 : getGeometria().hashCode());
		result = prime * result + ((getNombre() == null) ? 0 : getNombre().hashCode());
		result = prime * result + ((getNombreVia() == null) ? 0 : getNombreVia().hashCode());
		result = prime * result + ((getNumero() == null) ? 0 : getNumero().hashCode());
		result = prime * result + ((getLetra() == null) ? 0 : getLetra().hashCode());
		result = prime * result + ((getInterior() == null) ? 0 : getInterior().hashCode());
		result = prime * result + ((getGiro() == null) ? 0 : getGiro().hashCode());
		result = prime * result + ((getPublico() == null) ? 0 : getPublico().hashCode());
		result = prime * result + ((getZona() == null) ? 0 : getZona().hashCode());
		result = prime * result + ((getTipo() == null) ? 0 : getTipo().hashCode());
		result = prime * result + ((getPuntoIni() == null) ? 0 : getPuntoIni().hashCode());
		result = prime * result + ((getPuntoFin() == null) ? 0 : getPuntoFin().hashCode());
		result = prime * result + ((getTramo() == null) ? 0 : getTramo().hashCode());
		result = prime * result + ((getViaIni() == null) ? 0 : getViaIni().hashCode());
		result = prime * result + ((getViaFin() == null) ? 0 : getViaFin().hashCode());
		result = prime * result + ((getSentido() == null) ? 0 : getSentido().hashCode());
		result = prime * result + ((getPercentil() == null) ? 0 : getPercentil().hashCode());
		result = prime * result + ((getLimite() == null) ? 0 : getLimite().hashCode());
		result = prime * result + ((getEspacios() == null) ? 0 : getEspacios().hashCode());
		result = prime * result + ((getSector() == null) ? 0 : getSector().hashCode());
		result = prime * result + ((getCuadra() == null) ? 0 : getCuadra().hashCode());
		result = prime * result + ((getLado() == null) ? 0 : getLado().hashCode());
		result = prime * result + ((getHoraPasoPromedio() == null) ? 0 : getHoraPasoPromedio().hashCode());
		result = prime * result + ((getDetalle() == null) ? 0 : getDetalle().hashCode());
		return result;
	}

	private String query;

	public String getQuery() {
		return query;
	}

	public void setQuery(String query) {
		this.query = query;
	}
	
	
	
}