package pe.gob.miraflores.mobile.domain.mapaincidencias;

import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

import pe.gob.miraflores.mobile.domain.catalogo.Catalogo;

public class MapaIncidenciasRegistro {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.ID_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer idIncidencia;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.ID_EVENTO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer idEvento;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.TIPO_EVENTO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer tipoEvento;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.SUB_TIPO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer subTipo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.FEC_HORA_INICIO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	@DateTimeFormat(pattern = "dd/MM/yyyy HH:mm:ss")
	private Date fecHoraInicio;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.FEC_HORA_FIN
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	@DateTimeFormat(pattern = "dd/MM/yyyy HH:mm:ss")
	private Date fecHoraFin;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.DESCRIPCION
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String descripcion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.SEVERIDAD
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String severidad;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.CALLE
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String calle;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.TIPO_DIRECCION
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer tipoDireccion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.DIRECCION_FINAL
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String direccionFinal;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.NOMBRE_CALLE_INICIO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String nombreCalleInicio;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.NOMBRE_CALLE_FIN
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String nombreCalleFin;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.FEC_REGISTRA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Date fecRegistra;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.FEC_MODIFICA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Date fecModifica;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.DES_USU_REGISTRA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String desUsuRegistra;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.DES_USU_MODIFICA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String desUsuModifica;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.DES_IP_REGISTRA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String desIpRegistra;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.DES_IP_MODIFICA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String desIpModifica;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.ID_TIPO_VIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer idTipoVia;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.CUADRA_EVENTO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer cuadraEvento;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.ID_VIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer idVia;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.ID_CASO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer idCasoVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.TIPO_CASO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer tipoCasoVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.SUB_TIPO_CASO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer subTipoCasoVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.TIPO_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer tipoIncidencia;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.ID_VIA_CATASTRO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer idViaCatastro;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.ID_TIPO_VIA_CATASTRO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer idTipoViaCatastro;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.ESTADO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String estado;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.TIPO_CIERRE
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String tipoCierre;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.DES_CALLLES
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String desCallles;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.USUARIO_REGISTRO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer usuarioRegistro;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.USUARIO_MODIFICA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer usuarioModifica;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.VISIBLE
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String visible;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.ID_DISPOSITIVO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String idDispositivo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.HORA_LLAMADA_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String horaLlamadaVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.NOMBRE_REPORTA_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String nombreReportaIncidencia;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.DIRECCION_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String direccionIncidencia;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.ACCIONES_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String accionesIncidencia;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.NOMBRE_RECEPCIONA_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String nombreRecepcionaIncidencia;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.DNI_RECEPCIONA_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String dniRecepcionaIncidencia;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.NRO_CASO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String nroCasoVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.TELEF_REPORTA_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String telefReportaIncidencia;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.INCIDENCIA_PRESENTADA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String incidenciaPresentada;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.MEDIO_INGRESO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private Integer medioIngreso;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.ESTADO_CALIF_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String estadoCalifVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.ESTADO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String estadoVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.DES_ESTADO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String desEstadoVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.SUB_ESTADO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String subEstadoVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.DES_SUB_ESTADO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String desSubEstadoVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.DES_ESTADO_CALIF_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String desEstadoCalifVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.UNID_INTERV_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String unidIntervVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.DES_UNID_INTERV_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String desUnidIntervVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.IMPORTANTE_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String importanteVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.LLAMADA_DEVUELTA_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String llamadaDevueltaVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.FECHA_HORA_ATENCION_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String fechaHoraAtencionVoxiva;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GEO_INCIDENCIA_MAP.IND_LEIDO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	private String indLeido;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.ID_INCIDENCIA
	 * @return  the value of GEO_INCIDENCIA_MAP.ID_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getIdIncidencia() {
		return idIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.ID_INCIDENCIA
	 * @param idIncidencia  the value for GEO_INCIDENCIA_MAP.ID_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setIdIncidencia(Integer idIncidencia) {
		this.idIncidencia = idIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.ID_EVENTO
	 * @return  the value of GEO_INCIDENCIA_MAP.ID_EVENTO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getIdEvento() {
		return idEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.ID_EVENTO
	 * @param idEvento  the value for GEO_INCIDENCIA_MAP.ID_EVENTO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setIdEvento(Integer idEvento) {
		this.idEvento = idEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.TIPO_EVENTO
	 * @return  the value of GEO_INCIDENCIA_MAP.TIPO_EVENTO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getTipoEvento() {
		return tipoEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.TIPO_EVENTO
	 * @param tipoEvento  the value for GEO_INCIDENCIA_MAP.TIPO_EVENTO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setTipoEvento(Integer tipoEvento) {
		this.tipoEvento = tipoEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.SUB_TIPO
	 * @return  the value of GEO_INCIDENCIA_MAP.SUB_TIPO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getSubTipo() {
		return subTipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.SUB_TIPO
	 * @param subTipo  the value for GEO_INCIDENCIA_MAP.SUB_TIPO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setSubTipo(Integer subTipo) {
		this.subTipo = subTipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.FEC_HORA_INICIO
	 * @return  the value of GEO_INCIDENCIA_MAP.FEC_HORA_INICIO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Date getFecHoraInicio() {
		return fecHoraInicio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.FEC_HORA_INICIO
	 * @param fecHoraInicio  the value for GEO_INCIDENCIA_MAP.FEC_HORA_INICIO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setFecHoraInicio(Date fecHoraInicio) {
		this.fecHoraInicio = fecHoraInicio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.FEC_HORA_FIN
	 * @return  the value of GEO_INCIDENCIA_MAP.FEC_HORA_FIN
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Date getFecHoraFin() {
		return fecHoraFin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.FEC_HORA_FIN
	 * @param fecHoraFin  the value for GEO_INCIDENCIA_MAP.FEC_HORA_FIN
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setFecHoraFin(Date fecHoraFin) {
		this.fecHoraFin = fecHoraFin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.DESCRIPCION
	 * @return  the value of GEO_INCIDENCIA_MAP.DESCRIPCION
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.DESCRIPCION
	 * @param descripcion  the value for GEO_INCIDENCIA_MAP.DESCRIPCION
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.SEVERIDAD
	 * @return  the value of GEO_INCIDENCIA_MAP.SEVERIDAD
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getSeveridad() {
		return severidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.SEVERIDAD
	 * @param severidad  the value for GEO_INCIDENCIA_MAP.SEVERIDAD
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setSeveridad(String severidad) {
		this.severidad = severidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.CALLE
	 * @return  the value of GEO_INCIDENCIA_MAP.CALLE
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getCalle() {
		return calle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.CALLE
	 * @param calle  the value for GEO_INCIDENCIA_MAP.CALLE
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setCalle(String calle) {
		this.calle = calle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.TIPO_DIRECCION
	 * @return  the value of GEO_INCIDENCIA_MAP.TIPO_DIRECCION
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getTipoDireccion() {
		return tipoDireccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.TIPO_DIRECCION
	 * @param tipoDireccion  the value for GEO_INCIDENCIA_MAP.TIPO_DIRECCION
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setTipoDireccion(Integer tipoDireccion) {
		this.tipoDireccion = tipoDireccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.DIRECCION_FINAL
	 * @return  the value of GEO_INCIDENCIA_MAP.DIRECCION_FINAL
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getDireccionFinal() {
		return direccionFinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.DIRECCION_FINAL
	 * @param direccionFinal  the value for GEO_INCIDENCIA_MAP.DIRECCION_FINAL
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setDireccionFinal(String direccionFinal) {
		this.direccionFinal = direccionFinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.NOMBRE_CALLE_INICIO
	 * @return  the value of GEO_INCIDENCIA_MAP.NOMBRE_CALLE_INICIO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getNombreCalleInicio() {
		return nombreCalleInicio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.NOMBRE_CALLE_INICIO
	 * @param nombreCalleInicio  the value for GEO_INCIDENCIA_MAP.NOMBRE_CALLE_INICIO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setNombreCalleInicio(String nombreCalleInicio) {
		this.nombreCalleInicio = nombreCalleInicio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.NOMBRE_CALLE_FIN
	 * @return  the value of GEO_INCIDENCIA_MAP.NOMBRE_CALLE_FIN
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getNombreCalleFin() {
		return nombreCalleFin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.NOMBRE_CALLE_FIN
	 * @param nombreCalleFin  the value for GEO_INCIDENCIA_MAP.NOMBRE_CALLE_FIN
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setNombreCalleFin(String nombreCalleFin) {
		this.nombreCalleFin = nombreCalleFin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.FEC_REGISTRA
	 * @return  the value of GEO_INCIDENCIA_MAP.FEC_REGISTRA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Date getFecRegistra() {
		return fecRegistra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.FEC_REGISTRA
	 * @param fecRegistra  the value for GEO_INCIDENCIA_MAP.FEC_REGISTRA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setFecRegistra(Date fecRegistra) {
		this.fecRegistra = fecRegistra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.FEC_MODIFICA
	 * @return  the value of GEO_INCIDENCIA_MAP.FEC_MODIFICA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Date getFecModifica() {
		return fecModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.FEC_MODIFICA
	 * @param fecModifica  the value for GEO_INCIDENCIA_MAP.FEC_MODIFICA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setFecModifica(Date fecModifica) {
		this.fecModifica = fecModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.DES_USU_REGISTRA
	 * @return  the value of GEO_INCIDENCIA_MAP.DES_USU_REGISTRA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getDesUsuRegistra() {
		return desUsuRegistra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.DES_USU_REGISTRA
	 * @param desUsuRegistra  the value for GEO_INCIDENCIA_MAP.DES_USU_REGISTRA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setDesUsuRegistra(String desUsuRegistra) {
		this.desUsuRegistra = desUsuRegistra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.DES_USU_MODIFICA
	 * @return  the value of GEO_INCIDENCIA_MAP.DES_USU_MODIFICA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getDesUsuModifica() {
		return desUsuModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.DES_USU_MODIFICA
	 * @param desUsuModifica  the value for GEO_INCIDENCIA_MAP.DES_USU_MODIFICA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setDesUsuModifica(String desUsuModifica) {
		this.desUsuModifica = desUsuModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.DES_IP_REGISTRA
	 * @return  the value of GEO_INCIDENCIA_MAP.DES_IP_REGISTRA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getDesIpRegistra() {
		return desIpRegistra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.DES_IP_REGISTRA
	 * @param desIpRegistra  the value for GEO_INCIDENCIA_MAP.DES_IP_REGISTRA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setDesIpRegistra(String desIpRegistra) {
		this.desIpRegistra = desIpRegistra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.DES_IP_MODIFICA
	 * @return  the value of GEO_INCIDENCIA_MAP.DES_IP_MODIFICA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getDesIpModifica() {
		return desIpModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.DES_IP_MODIFICA
	 * @param desIpModifica  the value for GEO_INCIDENCIA_MAP.DES_IP_MODIFICA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setDesIpModifica(String desIpModifica) {
		this.desIpModifica = desIpModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.ID_TIPO_VIA
	 * @return  the value of GEO_INCIDENCIA_MAP.ID_TIPO_VIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getIdTipoVia() {
		return idTipoVia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.ID_TIPO_VIA
	 * @param idTipoVia  the value for GEO_INCIDENCIA_MAP.ID_TIPO_VIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setIdTipoVia(Integer idTipoVia) {
		this.idTipoVia = idTipoVia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.CUADRA_EVENTO
	 * @return  the value of GEO_INCIDENCIA_MAP.CUADRA_EVENTO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getCuadraEvento() {
		return cuadraEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.CUADRA_EVENTO
	 * @param cuadraEvento  the value for GEO_INCIDENCIA_MAP.CUADRA_EVENTO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setCuadraEvento(Integer cuadraEvento) {
		this.cuadraEvento = cuadraEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.ID_VIA
	 * @return  the value of GEO_INCIDENCIA_MAP.ID_VIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getIdVia() {
		return idVia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.ID_VIA
	 * @param idVia  the value for GEO_INCIDENCIA_MAP.ID_VIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setIdVia(Integer idVia) {
		this.idVia = idVia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.ID_CASO_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.ID_CASO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getIdCasoVoxiva() {
		return idCasoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.ID_CASO_VOXIVA
	 * @param idCasoVoxiva  the value for GEO_INCIDENCIA_MAP.ID_CASO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setIdCasoVoxiva(Integer idCasoVoxiva) {
		this.idCasoVoxiva = idCasoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.TIPO_CASO_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.TIPO_CASO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getTipoCasoVoxiva() {
		return tipoCasoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.TIPO_CASO_VOXIVA
	 * @param tipoCasoVoxiva  the value for GEO_INCIDENCIA_MAP.TIPO_CASO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setTipoCasoVoxiva(Integer tipoCasoVoxiva) {
		this.tipoCasoVoxiva = tipoCasoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.SUB_TIPO_CASO_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.SUB_TIPO_CASO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getSubTipoCasoVoxiva() {
		return subTipoCasoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.SUB_TIPO_CASO_VOXIVA
	 * @param subTipoCasoVoxiva  the value for GEO_INCIDENCIA_MAP.SUB_TIPO_CASO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setSubTipoCasoVoxiva(Integer subTipoCasoVoxiva) {
		this.subTipoCasoVoxiva = subTipoCasoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.TIPO_INCIDENCIA
	 * @return  the value of GEO_INCIDENCIA_MAP.TIPO_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getTipoIncidencia() {
		return tipoIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.TIPO_INCIDENCIA
	 * @param tipoIncidencia  the value for GEO_INCIDENCIA_MAP.TIPO_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setTipoIncidencia(Integer tipoIncidencia) {
		this.tipoIncidencia = tipoIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.ID_VIA_CATASTRO
	 * @return  the value of GEO_INCIDENCIA_MAP.ID_VIA_CATASTRO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getIdViaCatastro() {
		return idViaCatastro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.ID_VIA_CATASTRO
	 * @param idViaCatastro  the value for GEO_INCIDENCIA_MAP.ID_VIA_CATASTRO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setIdViaCatastro(Integer idViaCatastro) {
		this.idViaCatastro = idViaCatastro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.ID_TIPO_VIA_CATASTRO
	 * @return  the value of GEO_INCIDENCIA_MAP.ID_TIPO_VIA_CATASTRO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getIdTipoViaCatastro() {
		return idTipoViaCatastro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.ID_TIPO_VIA_CATASTRO
	 * @param idTipoViaCatastro  the value for GEO_INCIDENCIA_MAP.ID_TIPO_VIA_CATASTRO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setIdTipoViaCatastro(Integer idTipoViaCatastro) {
		this.idTipoViaCatastro = idTipoViaCatastro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.ESTADO
	 * @return  the value of GEO_INCIDENCIA_MAP.ESTADO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getEstado() {
		return estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.ESTADO
	 * @param estado  the value for GEO_INCIDENCIA_MAP.ESTADO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setEstado(String estado) {
		this.estado = estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.TIPO_CIERRE
	 * @return  the value of GEO_INCIDENCIA_MAP.TIPO_CIERRE
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getTipoCierre() {
		return tipoCierre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.TIPO_CIERRE
	 * @param tipoCierre  the value for GEO_INCIDENCIA_MAP.TIPO_CIERRE
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setTipoCierre(String tipoCierre) {
		this.tipoCierre = tipoCierre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.DES_CALLLES
	 * @return  the value of GEO_INCIDENCIA_MAP.DES_CALLLES
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getDesCallles() {
		return desCallles;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.DES_CALLLES
	 * @param desCallles  the value for GEO_INCIDENCIA_MAP.DES_CALLLES
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setDesCallles(String desCallles) {
		this.desCallles = desCallles;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.USUARIO_REGISTRO
	 * @return  the value of GEO_INCIDENCIA_MAP.USUARIO_REGISTRO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getUsuarioRegistro() {
		return usuarioRegistro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.USUARIO_REGISTRO
	 * @param usuarioRegistro  the value for GEO_INCIDENCIA_MAP.USUARIO_REGISTRO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setUsuarioRegistro(Integer usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.USUARIO_MODIFICA
	 * @return  the value of GEO_INCIDENCIA_MAP.USUARIO_MODIFICA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getUsuarioModifica() {
		return usuarioModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.USUARIO_MODIFICA
	 * @param usuarioModifica  the value for GEO_INCIDENCIA_MAP.USUARIO_MODIFICA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.VISIBLE
	 * @return  the value of GEO_INCIDENCIA_MAP.VISIBLE
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getVisible() {
		return visible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.VISIBLE
	 * @param visible  the value for GEO_INCIDENCIA_MAP.VISIBLE
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setVisible(String visible) {
		this.visible = visible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.ID_DISPOSITIVO
	 * @return  the value of GEO_INCIDENCIA_MAP.ID_DISPOSITIVO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getIdDispositivo() {
		return idDispositivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.ID_DISPOSITIVO
	 * @param idDispositivo  the value for GEO_INCIDENCIA_MAP.ID_DISPOSITIVO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setIdDispositivo(String idDispositivo) {
		this.idDispositivo = idDispositivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.HORA_LLAMADA_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.HORA_LLAMADA_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getHoraLlamadaVoxiva() {
		return horaLlamadaVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.HORA_LLAMADA_VOXIVA
	 * @param horaLlamadaVoxiva  the value for GEO_INCIDENCIA_MAP.HORA_LLAMADA_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setHoraLlamadaVoxiva(String horaLlamadaVoxiva) {
		this.horaLlamadaVoxiva = horaLlamadaVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.NOMBRE_REPORTA_INCIDENCIA
	 * @return  the value of GEO_INCIDENCIA_MAP.NOMBRE_REPORTA_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getNombreReportaIncidencia() {
		return nombreReportaIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.NOMBRE_REPORTA_INCIDENCIA
	 * @param nombreReportaIncidencia  the value for GEO_INCIDENCIA_MAP.NOMBRE_REPORTA_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setNombreReportaIncidencia(String nombreReportaIncidencia) {
		this.nombreReportaIncidencia = nombreReportaIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.DIRECCION_INCIDENCIA
	 * @return  the value of GEO_INCIDENCIA_MAP.DIRECCION_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getDireccionIncidencia() {
		return direccionIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.DIRECCION_INCIDENCIA
	 * @param direccionIncidencia  the value for GEO_INCIDENCIA_MAP.DIRECCION_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setDireccionIncidencia(String direccionIncidencia) {
		this.direccionIncidencia = direccionIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.ACCIONES_INCIDENCIA
	 * @return  the value of GEO_INCIDENCIA_MAP.ACCIONES_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getAccionesIncidencia() {
		return accionesIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.ACCIONES_INCIDENCIA
	 * @param accionesIncidencia  the value for GEO_INCIDENCIA_MAP.ACCIONES_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setAccionesIncidencia(String accionesIncidencia) {
		this.accionesIncidencia = accionesIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.NOMBRE_RECEPCIONA_INCIDENCIA
	 * @return  the value of GEO_INCIDENCIA_MAP.NOMBRE_RECEPCIONA_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getNombreRecepcionaIncidencia() {
		return nombreRecepcionaIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.NOMBRE_RECEPCIONA_INCIDENCIA
	 * @param nombreRecepcionaIncidencia  the value for GEO_INCIDENCIA_MAP.NOMBRE_RECEPCIONA_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setNombreRecepcionaIncidencia(String nombreRecepcionaIncidencia) {
		this.nombreRecepcionaIncidencia = nombreRecepcionaIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.DNI_RECEPCIONA_INCIDENCIA
	 * @return  the value of GEO_INCIDENCIA_MAP.DNI_RECEPCIONA_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getDniRecepcionaIncidencia() {
		return dniRecepcionaIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.DNI_RECEPCIONA_INCIDENCIA
	 * @param dniRecepcionaIncidencia  the value for GEO_INCIDENCIA_MAP.DNI_RECEPCIONA_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setDniRecepcionaIncidencia(String dniRecepcionaIncidencia) {
		this.dniRecepcionaIncidencia = dniRecepcionaIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.NRO_CASO_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.NRO_CASO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getNroCasoVoxiva() {
		return nroCasoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.NRO_CASO_VOXIVA
	 * @param nroCasoVoxiva  the value for GEO_INCIDENCIA_MAP.NRO_CASO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setNroCasoVoxiva(String nroCasoVoxiva) {
		this.nroCasoVoxiva = nroCasoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.TELEF_REPORTA_INCIDENCIA
	 * @return  the value of GEO_INCIDENCIA_MAP.TELEF_REPORTA_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getTelefReportaIncidencia() {
		return telefReportaIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.TELEF_REPORTA_INCIDENCIA
	 * @param telefReportaIncidencia  the value for GEO_INCIDENCIA_MAP.TELEF_REPORTA_INCIDENCIA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setTelefReportaIncidencia(String telefReportaIncidencia) {
		this.telefReportaIncidencia = telefReportaIncidencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.INCIDENCIA_PRESENTADA
	 * @return  the value of GEO_INCIDENCIA_MAP.INCIDENCIA_PRESENTADA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getIncidenciaPresentada() {
		return incidenciaPresentada;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.INCIDENCIA_PRESENTADA
	 * @param incidenciaPresentada  the value for GEO_INCIDENCIA_MAP.INCIDENCIA_PRESENTADA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setIncidenciaPresentada(String incidenciaPresentada) {
		this.incidenciaPresentada = incidenciaPresentada;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.MEDIO_INGRESO
	 * @return  the value of GEO_INCIDENCIA_MAP.MEDIO_INGRESO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public Integer getMedioIngreso() {
		return medioIngreso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.MEDIO_INGRESO
	 * @param medioIngreso  the value for GEO_INCIDENCIA_MAP.MEDIO_INGRESO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setMedioIngreso(Integer medioIngreso) {
		this.medioIngreso = medioIngreso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.ESTADO_CALIF_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.ESTADO_CALIF_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getEstadoCalifVoxiva() {
		return estadoCalifVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.ESTADO_CALIF_VOXIVA
	 * @param estadoCalifVoxiva  the value for GEO_INCIDENCIA_MAP.ESTADO_CALIF_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setEstadoCalifVoxiva(String estadoCalifVoxiva) {
		this.estadoCalifVoxiva = estadoCalifVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.ESTADO_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.ESTADO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getEstadoVoxiva() {
		return estadoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.ESTADO_VOXIVA
	 * @param estadoVoxiva  the value for GEO_INCIDENCIA_MAP.ESTADO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setEstadoVoxiva(String estadoVoxiva) {
		this.estadoVoxiva = estadoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.DES_ESTADO_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.DES_ESTADO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getDesEstadoVoxiva() {
		return desEstadoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.DES_ESTADO_VOXIVA
	 * @param desEstadoVoxiva  the value for GEO_INCIDENCIA_MAP.DES_ESTADO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setDesEstadoVoxiva(String desEstadoVoxiva) {
		this.desEstadoVoxiva = desEstadoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.SUB_ESTADO_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.SUB_ESTADO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getSubEstadoVoxiva() {
		return subEstadoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.SUB_ESTADO_VOXIVA
	 * @param subEstadoVoxiva  the value for GEO_INCIDENCIA_MAP.SUB_ESTADO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setSubEstadoVoxiva(String subEstadoVoxiva) {
		this.subEstadoVoxiva = subEstadoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.DES_SUB_ESTADO_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.DES_SUB_ESTADO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getDesSubEstadoVoxiva() {
		return desSubEstadoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.DES_SUB_ESTADO_VOXIVA
	 * @param desSubEstadoVoxiva  the value for GEO_INCIDENCIA_MAP.DES_SUB_ESTADO_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setDesSubEstadoVoxiva(String desSubEstadoVoxiva) {
		this.desSubEstadoVoxiva = desSubEstadoVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.DES_ESTADO_CALIF_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.DES_ESTADO_CALIF_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getDesEstadoCalifVoxiva() {
		return desEstadoCalifVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.DES_ESTADO_CALIF_VOXIVA
	 * @param desEstadoCalifVoxiva  the value for GEO_INCIDENCIA_MAP.DES_ESTADO_CALIF_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setDesEstadoCalifVoxiva(String desEstadoCalifVoxiva) {
		this.desEstadoCalifVoxiva = desEstadoCalifVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.UNID_INTERV_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.UNID_INTERV_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getUnidIntervVoxiva() {
		return unidIntervVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.UNID_INTERV_VOXIVA
	 * @param unidIntervVoxiva  the value for GEO_INCIDENCIA_MAP.UNID_INTERV_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setUnidIntervVoxiva(String unidIntervVoxiva) {
		this.unidIntervVoxiva = unidIntervVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.DES_UNID_INTERV_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.DES_UNID_INTERV_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getDesUnidIntervVoxiva() {
		return desUnidIntervVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.DES_UNID_INTERV_VOXIVA
	 * @param desUnidIntervVoxiva  the value for GEO_INCIDENCIA_MAP.DES_UNID_INTERV_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setDesUnidIntervVoxiva(String desUnidIntervVoxiva) {
		this.desUnidIntervVoxiva = desUnidIntervVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.IMPORTANTE_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.IMPORTANTE_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getImportanteVoxiva() {
		return importanteVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.IMPORTANTE_VOXIVA
	 * @param importanteVoxiva  the value for GEO_INCIDENCIA_MAP.IMPORTANTE_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setImportanteVoxiva(String importanteVoxiva) {
		this.importanteVoxiva = importanteVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.LLAMADA_DEVUELTA_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.LLAMADA_DEVUELTA_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getLlamadaDevueltaVoxiva() {
		return llamadaDevueltaVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.LLAMADA_DEVUELTA_VOXIVA
	 * @param llamadaDevueltaVoxiva  the value for GEO_INCIDENCIA_MAP.LLAMADA_DEVUELTA_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setLlamadaDevueltaVoxiva(String llamadaDevueltaVoxiva) {
		this.llamadaDevueltaVoxiva = llamadaDevueltaVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.FECHA_HORA_ATENCION_VOXIVA
	 * @return  the value of GEO_INCIDENCIA_MAP.FECHA_HORA_ATENCION_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getFechaHoraAtencionVoxiva() {
		return fechaHoraAtencionVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.FECHA_HORA_ATENCION_VOXIVA
	 * @param fechaHoraAtencionVoxiva  the value for GEO_INCIDENCIA_MAP.FECHA_HORA_ATENCION_VOXIVA
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setFechaHoraAtencionVoxiva(String fechaHoraAtencionVoxiva) {
		this.fechaHoraAtencionVoxiva = fechaHoraAtencionVoxiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GEO_INCIDENCIA_MAP.IND_LEIDO
	 * @return  the value of GEO_INCIDENCIA_MAP.IND_LEIDO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public String getIndLeido() {
		return indLeido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GEO_INCIDENCIA_MAP.IND_LEIDO
	 * @param indLeido  the value for GEO_INCIDENCIA_MAP.IND_LEIDO
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	public void setIndLeido(String indLeido) {
		this.indLeido = indLeido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		MapaIncidenciasRegistro other = (MapaIncidenciasRegistro) that;
		return (this.getIdIncidencia() == null ? other.getIdIncidencia() == null
				: this.getIdIncidencia().equals(other.getIdIncidencia()))
				&& (this.getIdEvento() == null ? other.getIdEvento() == null
						: this.getIdEvento().equals(other.getIdEvento()))
				&& (this.getTipoEvento() == null ? other.getTipoEvento() == null
						: this.getTipoEvento().equals(other.getTipoEvento()))
				&& (this.getSubTipo() == null ? other.getSubTipo() == null
						: this.getSubTipo().equals(other.getSubTipo()))
				&& (this.getFecHoraInicio() == null ? other.getFecHoraInicio() == null
						: this.getFecHoraInicio().equals(other.getFecHoraInicio()))
				&& (this.getFecHoraFin() == null ? other.getFecHoraFin() == null
						: this.getFecHoraFin().equals(other.getFecHoraFin()))
				&& (this.getDescripcion() == null ? other.getDescripcion() == null
						: this.getDescripcion().equals(other.getDescripcion()))
				&& (this.getSeveridad() == null ? other.getSeveridad() == null
						: this.getSeveridad().equals(other.getSeveridad()))
				&& (this.getCalle() == null ? other.getCalle() == null : this.getCalle().equals(other.getCalle()))
				&& (this.getTipoDireccion() == null ? other.getTipoDireccion() == null
						: this.getTipoDireccion().equals(other.getTipoDireccion()))
				&& (this.getDireccionFinal() == null ? other.getDireccionFinal() == null
						: this.getDireccionFinal().equals(other.getDireccionFinal()))
				&& (this.getNombreCalleInicio() == null ? other.getNombreCalleInicio() == null
						: this.getNombreCalleInicio().equals(other.getNombreCalleInicio()))
				&& (this.getNombreCalleFin() == null ? other.getNombreCalleFin() == null
						: this.getNombreCalleFin().equals(other.getNombreCalleFin()))
				&& (this.getFecRegistra() == null ? other.getFecRegistra() == null
						: this.getFecRegistra().equals(other.getFecRegistra()))
				&& (this.getFecModifica() == null ? other.getFecModifica() == null
						: this.getFecModifica().equals(other.getFecModifica()))
				&& (this.getDesUsuRegistra() == null ? other.getDesUsuRegistra() == null
						: this.getDesUsuRegistra().equals(other.getDesUsuRegistra()))
				&& (this.getDesUsuModifica() == null ? other.getDesUsuModifica() == null
						: this.getDesUsuModifica().equals(other.getDesUsuModifica()))
				&& (this.getDesIpRegistra() == null ? other.getDesIpRegistra() == null
						: this.getDesIpRegistra().equals(other.getDesIpRegistra()))
				&& (this.getDesIpModifica() == null ? other.getDesIpModifica() == null
						: this.getDesIpModifica().equals(other.getDesIpModifica()))
				&& (this.getIdTipoVia() == null ? other.getIdTipoVia() == null
						: this.getIdTipoVia().equals(other.getIdTipoVia()))
				&& (this.getCuadraEvento() == null ? other.getCuadraEvento() == null
						: this.getCuadraEvento().equals(other.getCuadraEvento()))
				&& (this.getIdVia() == null ? other.getIdVia() == null : this.getIdVia().equals(other.getIdVia()))
				&& (this.getIdCasoVoxiva() == null ? other.getIdCasoVoxiva() == null
						: this.getIdCasoVoxiva().equals(other.getIdCasoVoxiva()))
				&& (this.getTipoCasoVoxiva() == null ? other.getTipoCasoVoxiva() == null
						: this.getTipoCasoVoxiva().equals(other.getTipoCasoVoxiva()))
				&& (this.getSubTipoCasoVoxiva() == null ? other.getSubTipoCasoVoxiva() == null
						: this.getSubTipoCasoVoxiva().equals(other.getSubTipoCasoVoxiva()))
				&& (this.getTipoIncidencia() == null ? other.getTipoIncidencia() == null
						: this.getTipoIncidencia().equals(other.getTipoIncidencia()))
				&& (this.getIdViaCatastro() == null ? other.getIdViaCatastro() == null
						: this.getIdViaCatastro().equals(other.getIdViaCatastro()))
				&& (this.getIdTipoViaCatastro() == null ? other.getIdTipoViaCatastro() == null
						: this.getIdTipoViaCatastro().equals(other.getIdTipoViaCatastro()))
				&& (this.getEstado() == null ? other.getEstado() == null : this.getEstado().equals(other.getEstado()))
				&& (this.getTipoCierre() == null ? other.getTipoCierre() == null
						: this.getTipoCierre().equals(other.getTipoCierre()))
				&& (this.getDesCallles() == null ? other.getDesCallles() == null
						: this.getDesCallles().equals(other.getDesCallles()))
				&& (this.getUsuarioRegistro() == null ? other.getUsuarioRegistro() == null
						: this.getUsuarioRegistro().equals(other.getUsuarioRegistro()))
				&& (this.getUsuarioModifica() == null ? other.getUsuarioModifica() == null
						: this.getUsuarioModifica().equals(other.getUsuarioModifica()))
				&& (this.getVisible() == null ? other.getVisible() == null
						: this.getVisible().equals(other.getVisible()))
				&& (this.getIdDispositivo() == null ? other.getIdDispositivo() == null
						: this.getIdDispositivo().equals(other.getIdDispositivo()))
				&& (this.getHoraLlamadaVoxiva() == null ? other.getHoraLlamadaVoxiva() == null
						: this.getHoraLlamadaVoxiva().equals(other.getHoraLlamadaVoxiva()))
				&& (this.getNombreReportaIncidencia() == null ? other.getNombreReportaIncidencia() == null
						: this.getNombreReportaIncidencia().equals(other.getNombreReportaIncidencia()))
				&& (this.getDireccionIncidencia() == null ? other.getDireccionIncidencia() == null
						: this.getDireccionIncidencia().equals(other.getDireccionIncidencia()))
				&& (this.getAccionesIncidencia() == null ? other.getAccionesIncidencia() == null
						: this.getAccionesIncidencia().equals(other.getAccionesIncidencia()))
				&& (this.getNombreRecepcionaIncidencia() == null ? other.getNombreRecepcionaIncidencia() == null
						: this.getNombreRecepcionaIncidencia().equals(other.getNombreRecepcionaIncidencia()))
				&& (this.getDniRecepcionaIncidencia() == null ? other.getDniRecepcionaIncidencia() == null
						: this.getDniRecepcionaIncidencia().equals(other.getDniRecepcionaIncidencia()))
				&& (this.getNroCasoVoxiva() == null ? other.getNroCasoVoxiva() == null
						: this.getNroCasoVoxiva().equals(other.getNroCasoVoxiva()))
				&& (this.getTelefReportaIncidencia() == null ? other.getTelefReportaIncidencia() == null
						: this.getTelefReportaIncidencia().equals(other.getTelefReportaIncidencia()))
				&& (this.getIncidenciaPresentada() == null ? other.getIncidenciaPresentada() == null
						: this.getIncidenciaPresentada().equals(other.getIncidenciaPresentada()))
				&& (this.getMedioIngreso() == null ? other.getMedioIngreso() == null
						: this.getMedioIngreso().equals(other.getMedioIngreso()))
				&& (this.getEstadoCalifVoxiva() == null ? other.getEstadoCalifVoxiva() == null
						: this.getEstadoCalifVoxiva().equals(other.getEstadoCalifVoxiva()))
				&& (this.getEstadoVoxiva() == null ? other.getEstadoVoxiva() == null
						: this.getEstadoVoxiva().equals(other.getEstadoVoxiva()))
				&& (this.getDesEstadoVoxiva() == null ? other.getDesEstadoVoxiva() == null
						: this.getDesEstadoVoxiva().equals(other.getDesEstadoVoxiva()))
				&& (this.getSubEstadoVoxiva() == null ? other.getSubEstadoVoxiva() == null
						: this.getSubEstadoVoxiva().equals(other.getSubEstadoVoxiva()))
				&& (this.getDesSubEstadoVoxiva() == null ? other.getDesSubEstadoVoxiva() == null
						: this.getDesSubEstadoVoxiva().equals(other.getDesSubEstadoVoxiva()))
				&& (this.getDesEstadoCalifVoxiva() == null ? other.getDesEstadoCalifVoxiva() == null
						: this.getDesEstadoCalifVoxiva().equals(other.getDesEstadoCalifVoxiva()))
				&& (this.getUnidIntervVoxiva() == null ? other.getUnidIntervVoxiva() == null
						: this.getUnidIntervVoxiva().equals(other.getUnidIntervVoxiva()))
				&& (this.getDesUnidIntervVoxiva() == null ? other.getDesUnidIntervVoxiva() == null
						: this.getDesUnidIntervVoxiva().equals(other.getDesUnidIntervVoxiva()))
				&& (this.getImportanteVoxiva() == null ? other.getImportanteVoxiva() == null
						: this.getImportanteVoxiva().equals(other.getImportanteVoxiva()))
				&& (this.getLlamadaDevueltaVoxiva() == null ? other.getLlamadaDevueltaVoxiva() == null
						: this.getLlamadaDevueltaVoxiva().equals(other.getLlamadaDevueltaVoxiva()))
				&& (this.getFechaHoraAtencionVoxiva() == null ? other.getFechaHoraAtencionVoxiva() == null
						: this.getFechaHoraAtencionVoxiva().equals(other.getFechaHoraAtencionVoxiva()))
				&& (this.getIndLeido() == null ? other.getIndLeido() == null
						: this.getIndLeido().equals(other.getIndLeido()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_INCIDENCIA_MAP
	 * @mbggenerated  Wed Aug 10 12:32:50 COT 2016
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getIdIncidencia() == null) ? 0 : getIdIncidencia().hashCode());
		result = prime * result + ((getIdEvento() == null) ? 0 : getIdEvento().hashCode());
		result = prime * result + ((getTipoEvento() == null) ? 0 : getTipoEvento().hashCode());
		result = prime * result + ((getSubTipo() == null) ? 0 : getSubTipo().hashCode());
		result = prime * result + ((getFecHoraInicio() == null) ? 0 : getFecHoraInicio().hashCode());
		result = prime * result + ((getFecHoraFin() == null) ? 0 : getFecHoraFin().hashCode());
		result = prime * result + ((getDescripcion() == null) ? 0 : getDescripcion().hashCode());
		result = prime * result + ((getSeveridad() == null) ? 0 : getSeveridad().hashCode());
		result = prime * result + ((getCalle() == null) ? 0 : getCalle().hashCode());
		result = prime * result + ((getTipoDireccion() == null) ? 0 : getTipoDireccion().hashCode());
		result = prime * result + ((getDireccionFinal() == null) ? 0 : getDireccionFinal().hashCode());
		result = prime * result + ((getNombreCalleInicio() == null) ? 0 : getNombreCalleInicio().hashCode());
		result = prime * result + ((getNombreCalleFin() == null) ? 0 : getNombreCalleFin().hashCode());
		result = prime * result + ((getFecRegistra() == null) ? 0 : getFecRegistra().hashCode());
		result = prime * result + ((getFecModifica() == null) ? 0 : getFecModifica().hashCode());
		result = prime * result + ((getDesUsuRegistra() == null) ? 0 : getDesUsuRegistra().hashCode());
		result = prime * result + ((getDesUsuModifica() == null) ? 0 : getDesUsuModifica().hashCode());
		result = prime * result + ((getDesIpRegistra() == null) ? 0 : getDesIpRegistra().hashCode());
		result = prime * result + ((getDesIpModifica() == null) ? 0 : getDesIpModifica().hashCode());
		result = prime * result + ((getIdTipoVia() == null) ? 0 : getIdTipoVia().hashCode());
		result = prime * result + ((getCuadraEvento() == null) ? 0 : getCuadraEvento().hashCode());
		result = prime * result + ((getIdVia() == null) ? 0 : getIdVia().hashCode());
		result = prime * result + ((getIdCasoVoxiva() == null) ? 0 : getIdCasoVoxiva().hashCode());
		result = prime * result + ((getTipoCasoVoxiva() == null) ? 0 : getTipoCasoVoxiva().hashCode());
		result = prime * result + ((getSubTipoCasoVoxiva() == null) ? 0 : getSubTipoCasoVoxiva().hashCode());
		result = prime * result + ((getTipoIncidencia() == null) ? 0 : getTipoIncidencia().hashCode());
		result = prime * result + ((getIdViaCatastro() == null) ? 0 : getIdViaCatastro().hashCode());
		result = prime * result + ((getIdTipoViaCatastro() == null) ? 0 : getIdTipoViaCatastro().hashCode());
		result = prime * result + ((getEstado() == null) ? 0 : getEstado().hashCode());
		result = prime * result + ((getTipoCierre() == null) ? 0 : getTipoCierre().hashCode());
		result = prime * result + ((getDesCallles() == null) ? 0 : getDesCallles().hashCode());
		result = prime * result + ((getUsuarioRegistro() == null) ? 0 : getUsuarioRegistro().hashCode());
		result = prime * result + ((getUsuarioModifica() == null) ? 0 : getUsuarioModifica().hashCode());
		result = prime * result + ((getVisible() == null) ? 0 : getVisible().hashCode());
		result = prime * result + ((getIdDispositivo() == null) ? 0 : getIdDispositivo().hashCode());
		result = prime * result + ((getHoraLlamadaVoxiva() == null) ? 0 : getHoraLlamadaVoxiva().hashCode());
		result = prime * result
				+ ((getNombreReportaIncidencia() == null) ? 0 : getNombreReportaIncidencia().hashCode());
		result = prime * result + ((getDireccionIncidencia() == null) ? 0 : getDireccionIncidencia().hashCode());
		result = prime * result + ((getAccionesIncidencia() == null) ? 0 : getAccionesIncidencia().hashCode());
		result = prime * result
				+ ((getNombreRecepcionaIncidencia() == null) ? 0 : getNombreRecepcionaIncidencia().hashCode());
		result = prime * result
				+ ((getDniRecepcionaIncidencia() == null) ? 0 : getDniRecepcionaIncidencia().hashCode());
		result = prime * result + ((getNroCasoVoxiva() == null) ? 0 : getNroCasoVoxiva().hashCode());
		result = prime * result + ((getTelefReportaIncidencia() == null) ? 0 : getTelefReportaIncidencia().hashCode());
		result = prime * result + ((getIncidenciaPresentada() == null) ? 0 : getIncidenciaPresentada().hashCode());
		result = prime * result + ((getMedioIngreso() == null) ? 0 : getMedioIngreso().hashCode());
		result = prime * result + ((getEstadoCalifVoxiva() == null) ? 0 : getEstadoCalifVoxiva().hashCode());
		result = prime * result + ((getEstadoVoxiva() == null) ? 0 : getEstadoVoxiva().hashCode());
		result = prime * result + ((getDesEstadoVoxiva() == null) ? 0 : getDesEstadoVoxiva().hashCode());
		result = prime * result + ((getSubEstadoVoxiva() == null) ? 0 : getSubEstadoVoxiva().hashCode());
		result = prime * result + ((getDesSubEstadoVoxiva() == null) ? 0 : getDesSubEstadoVoxiva().hashCode());
		result = prime * result + ((getDesEstadoCalifVoxiva() == null) ? 0 : getDesEstadoCalifVoxiva().hashCode());
		result = prime * result + ((getUnidIntervVoxiva() == null) ? 0 : getUnidIntervVoxiva().hashCode());
		result = prime * result + ((getDesUnidIntervVoxiva() == null) ? 0 : getDesUnidIntervVoxiva().hashCode());
		result = prime * result + ((getImportanteVoxiva() == null) ? 0 : getImportanteVoxiva().hashCode());
		result = prime * result + ((getLlamadaDevueltaVoxiva() == null) ? 0 : getLlamadaDevueltaVoxiva().hashCode());
		result = prime * result
				+ ((getFechaHoraAtencionVoxiva() == null) ? 0 : getFechaHoraAtencionVoxiva().hashCode());
		result = prime * result + ((getIndLeido() == null) ? 0 : getIndLeido().hashCode());
		return result;
	}

	private List<MapaIncidenciasGeometria> detalleGeometria;
    
	private String latitud;
	
	private String longitud;
	
	private Catalogo tipo;
	
	private String nombreTipoEvento;
	
	private String desTipoIncidencia;

	private Integer start;
	
	private Integer limit;
	
	private String strFecIni;
	
	private String strFecFin;
	
	private Integer idUsuarioSesion;
	
	private Integer idPreRegistro;
	
	private List<GeometriaLinea> lineas;
	
	private String strFecLlamada;
	
	private String strHoraLlamada;
	
	private String strFecAtencion;
	
	private String strHoraAtencion;
	
	private String desMedioIngreso;
	
	private List<Integer> listEstadoCalifica;
	
	private List<Integer> listmedios;
	
	private String isXmlFormat;
	
	private MapaIncidenciasGeometria geometria;
	
	public String getLatitud() {
		return latitud;
	}
	
	public List<MapaIncidenciasGeometria> getDetalleGeometria() {
		return detalleGeometria;
	}

	public void setDetalleGeometria(List<MapaIncidenciasGeometria> detalleGeometria) {
		this.detalleGeometria = detalleGeometria;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	public String getLongitud() {
		return longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	public Catalogo getTipo() {
		return tipo;
	}

	public void setTipo(Catalogo tipo) {
		this.tipo = tipo;
	}

	public String getNombreTipoEvento() {
		return nombreTipoEvento;
	}

	public void setNombreTipoEvento(String nombreTipoEvento) {
		this.nombreTipoEvento = nombreTipoEvento;
	}

	public String getDesTipoIncidencia() {
		return desTipoIncidencia;
	}

	public void setDesTipoIncidencia(String desTipoIncidencia) {
		this.desTipoIncidencia = desTipoIncidencia;
	}

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	public String getStrFecIni() {
		return strFecIni;
	}

	public void setStrFecIni(String strFecIni) {
		this.strFecIni = strFecIni;
	}

	public String getStrFecFin() {
		return strFecFin;
	}

	public void setStrFecFin(String strFecFin) {
		this.strFecFin = strFecFin;
	}

	public Integer getIdUsuarioSesion() {
		return idUsuarioSesion;
	}

	public void setIdUsuarioSesion(Integer idUsuarioSesion) {
		this.idUsuarioSesion = idUsuarioSesion;
	}

	public List<GeometriaLinea> getLineas() {
		return lineas;
	}

	public void setLineas(List<GeometriaLinea> lineas) {
		this.lineas = lineas;
	}

	public Integer getIdPreRegistro() {
		return idPreRegistro;
	}

	public void setIdPreRegistro(Integer idPreRegistro) {
		this.idPreRegistro = idPreRegistro;
	}

	public String getStrFecLlamada() {
		return strFecLlamada;
	}

	public void setStrFecLlamada(String strFecLlamada) {
		this.strFecLlamada = strFecLlamada;
	}

	public String getStrHoraLlamada() {
		return strHoraLlamada;
	}

	public void setStrHoraLlamada(String strHoraLlamada) {
		this.strHoraLlamada = strHoraLlamada;
	}

	public String getStrFecAtencion() {
		return strFecAtencion;
	}

	public void setStrFecAtencion(String strFecAtencion) {
		this.strFecAtencion = strFecAtencion;
	}

	public String getStrHoraAtencion() {
		return strHoraAtencion;
	}

	public void setStrHoraAtencion(String strHoraAtencion) {
		this.strHoraAtencion = strHoraAtencion;
	}

	public String getDesMedioIngreso() {
		return desMedioIngreso;
	}

	public void setDesMedioIngreso(String desMedioIngreso) {
		this.desMedioIngreso = desMedioIngreso;
	}

	public List<Integer> getListEstadoCalifica() {
		return listEstadoCalifica;
	}

	public void setListEstadoCalifica(List<Integer> listEstadoCalifica) {
		this.listEstadoCalifica = listEstadoCalifica;
	}

	public List<Integer> getListmedios() {
		return listmedios;
	}

	public void setListmedios(List<Integer> listmedios) {
		this.listmedios = listmedios;
	}

	
	private List<MapaIncidenciaSchedule> dias;

	public List<MapaIncidenciaSchedule> getDias() {
		return dias;
	}

	public void setDias(List<MapaIncidenciaSchedule> dias) {
		this.dias = dias;
	}

	public String getIsXmlFormat() {
		return isXmlFormat;
	}

	public void setIsXmlFormat(String isXmlFormat) {
		this.isXmlFormat = isXmlFormat;
	}

	public MapaIncidenciasGeometria getGeometria() {
		return geometria;
	}

	public void setGeometria(MapaIncidenciasGeometria geometria) {
		this.geometria = geometria;
	}
	
	
	
	
}