package pe.gob.miraflores.mobile.domain.mapaincidencias;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MapaIncidenciaScheduleCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    public MapaIncidenciaScheduleCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaIsNull() {
            addCriterion("ID_INCIDENCIA is null");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaIsNotNull() {
            addCriterion("ID_INCIDENCIA is not null");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaEqualTo(Integer value) {
            addCriterion("ID_INCIDENCIA =", value, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaNotEqualTo(Integer value) {
            addCriterion("ID_INCIDENCIA <>", value, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaGreaterThan(Integer value) {
            addCriterion("ID_INCIDENCIA >", value, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_INCIDENCIA >=", value, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaLessThan(Integer value) {
            addCriterion("ID_INCIDENCIA <", value, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaLessThanOrEqualTo(Integer value) {
            addCriterion("ID_INCIDENCIA <=", value, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaIn(List<Integer> values) {
            addCriterion("ID_INCIDENCIA in", values, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaNotIn(List<Integer> values) {
            addCriterion("ID_INCIDENCIA not in", values, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaBetween(Integer value1, Integer value2) {
            addCriterion("ID_INCIDENCIA between", value1, value2, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_INCIDENCIA not between", value1, value2, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andHoraInicioIsNull() {
            addCriterion("HORA_INICIO is null");
            return (Criteria) this;
        }

        public Criteria andHoraInicioIsNotNull() {
            addCriterion("HORA_INICIO is not null");
            return (Criteria) this;
        }

        public Criteria andHoraInicioEqualTo(String value) {
            addCriterion("HORA_INICIO =", value, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioNotEqualTo(String value) {
            addCriterion("HORA_INICIO <>", value, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioGreaterThan(String value) {
            addCriterion("HORA_INICIO >", value, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioGreaterThanOrEqualTo(String value) {
            addCriterion("HORA_INICIO >=", value, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioLessThan(String value) {
            addCriterion("HORA_INICIO <", value, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioLessThanOrEqualTo(String value) {
            addCriterion("HORA_INICIO <=", value, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioLike(String value) {
            addCriterion("HORA_INICIO like", value, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioNotLike(String value) {
            addCriterion("HORA_INICIO not like", value, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioIn(List<String> values) {
            addCriterion("HORA_INICIO in", values, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioNotIn(List<String> values) {
            addCriterion("HORA_INICIO not in", values, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioBetween(String value1, String value2) {
            addCriterion("HORA_INICIO between", value1, value2, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioNotBetween(String value1, String value2) {
            addCriterion("HORA_INICIO not between", value1, value2, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraFinIsNull() {
            addCriterion("HORA_FIN is null");
            return (Criteria) this;
        }

        public Criteria andHoraFinIsNotNull() {
            addCriterion("HORA_FIN is not null");
            return (Criteria) this;
        }

        public Criteria andHoraFinEqualTo(String value) {
            addCriterion("HORA_FIN =", value, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinNotEqualTo(String value) {
            addCriterion("HORA_FIN <>", value, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinGreaterThan(String value) {
            addCriterion("HORA_FIN >", value, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinGreaterThanOrEqualTo(String value) {
            addCriterion("HORA_FIN >=", value, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinLessThan(String value) {
            addCriterion("HORA_FIN <", value, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinLessThanOrEqualTo(String value) {
            addCriterion("HORA_FIN <=", value, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinLike(String value) {
            addCriterion("HORA_FIN like", value, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinNotLike(String value) {
            addCriterion("HORA_FIN not like", value, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinIn(List<String> values) {
            addCriterion("HORA_FIN in", values, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinNotIn(List<String> values) {
            addCriterion("HORA_FIN not in", values, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinBetween(String value1, String value2) {
            addCriterion("HORA_FIN between", value1, value2, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinNotBetween(String value1, String value2) {
            addCriterion("HORA_FIN not between", value1, value2, "horaFin");
            return (Criteria) this;
        }

        public Criteria andDesDiaIsNull() {
            addCriterion("DES_DIA is null");
            return (Criteria) this;
        }

        public Criteria andDesDiaIsNotNull() {
            addCriterion("DES_DIA is not null");
            return (Criteria) this;
        }

        public Criteria andDesDiaEqualTo(String value) {
            addCriterion("DES_DIA =", value, "desDia");
            return (Criteria) this;
        }

        public Criteria andDesDiaNotEqualTo(String value) {
            addCriterion("DES_DIA <>", value, "desDia");
            return (Criteria) this;
        }

        public Criteria andDesDiaGreaterThan(String value) {
            addCriterion("DES_DIA >", value, "desDia");
            return (Criteria) this;
        }

        public Criteria andDesDiaGreaterThanOrEqualTo(String value) {
            addCriterion("DES_DIA >=", value, "desDia");
            return (Criteria) this;
        }

        public Criteria andDesDiaLessThan(String value) {
            addCriterion("DES_DIA <", value, "desDia");
            return (Criteria) this;
        }

        public Criteria andDesDiaLessThanOrEqualTo(String value) {
            addCriterion("DES_DIA <=", value, "desDia");
            return (Criteria) this;
        }

        public Criteria andDesDiaLike(String value) {
            addCriterion("DES_DIA like", value, "desDia");
            return (Criteria) this;
        }

        public Criteria andDesDiaNotLike(String value) {
            addCriterion("DES_DIA not like", value, "desDia");
            return (Criteria) this;
        }

        public Criteria andDesDiaIn(List<String> values) {
            addCriterion("DES_DIA in", values, "desDia");
            return (Criteria) this;
        }

        public Criteria andDesDiaNotIn(List<String> values) {
            addCriterion("DES_DIA not in", values, "desDia");
            return (Criteria) this;
        }

        public Criteria andDesDiaBetween(String value1, String value2) {
            addCriterion("DES_DIA between", value1, value2, "desDia");
            return (Criteria) this;
        }

        public Criteria andDesDiaNotBetween(String value1, String value2) {
            addCriterion("DES_DIA not between", value1, value2, "desDia");
            return (Criteria) this;
        }

        public Criteria andFecRegistraIsNull() {
            addCriterion("FEC_REGISTRA is null");
            return (Criteria) this;
        }

        public Criteria andFecRegistraIsNotNull() {
            addCriterion("FEC_REGISTRA is not null");
            return (Criteria) this;
        }

        public Criteria andFecRegistraEqualTo(Date value) {
            addCriterion("FEC_REGISTRA =", value, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraNotEqualTo(Date value) {
            addCriterion("FEC_REGISTRA <>", value, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraGreaterThan(Date value) {
            addCriterion("FEC_REGISTRA >", value, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraGreaterThanOrEqualTo(Date value) {
            addCriterion("FEC_REGISTRA >=", value, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraLessThan(Date value) {
            addCriterion("FEC_REGISTRA <", value, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraLessThanOrEqualTo(Date value) {
            addCriterion("FEC_REGISTRA <=", value, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraIn(List<Date> values) {
            addCriterion("FEC_REGISTRA in", values, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraNotIn(List<Date> values) {
            addCriterion("FEC_REGISTRA not in", values, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraBetween(Date value1, Date value2) {
            addCriterion("FEC_REGISTRA between", value1, value2, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andFecRegistraNotBetween(Date value1, Date value2) {
            addCriterion("FEC_REGISTRA not between", value1, value2, "fecRegistra");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("ESTADO is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("ESTADO is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(String value) {
            addCriterion("ESTADO =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(String value) {
            addCriterion("ESTADO <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(String value) {
            addCriterion("ESTADO >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(String value) {
            addCriterion("ESTADO >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(String value) {
            addCriterion("ESTADO <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(String value) {
            addCriterion("ESTADO <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLike(String value) {
            addCriterion("ESTADO like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotLike(String value) {
            addCriterion("ESTADO not like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<String> values) {
            addCriterion("ESTADO in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<String> values) {
            addCriterion("ESTADO not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(String value1, String value2) {
            addCriterion("ESTADO between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(String value1, String value2) {
            addCriterion("ESTADO not between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andHoraInicioLikeInsensitive(String value) {
            addCriterion("upper(HORA_INICIO) like", value.toUpperCase(), "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraFinLikeInsensitive(String value) {
            addCriterion("upper(HORA_FIN) like", value.toUpperCase(), "horaFin");
            return (Criteria) this;
        }

        public Criteria andDesDiaLikeInsensitive(String value) {
            addCriterion("upper(DES_DIA) like", value.toUpperCase(), "desDia");
            return (Criteria) this;
        }

        public Criteria andEstadoLikeInsensitive(String value) {
            addCriterion("upper(ESTADO) like", value.toUpperCase(), "estado");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 06 12:22:00 COT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}