package pe.gob.miraflores.mobile.domain.mapaincidencias;

import java.util.ArrayList;
import java.util.List;

public class MapaIncidenciaGenericoCriteria {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public MapaIncidenciaGenericoCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andGeometriaIsNull() {
			addCriterion("GEOMETRIA is null");
			return (Criteria) this;
		}

		public Criteria andGeometriaIsNotNull() {
			addCriterion("GEOMETRIA is not null");
			return (Criteria) this;
		}

		public Criteria andGeometriaEqualTo(String value) {
			addCriterion("GEOMETRIA =", value, "geometria");
			return (Criteria) this;
		}

		public Criteria andGeometriaNotEqualTo(String value) {
			addCriterion("GEOMETRIA <>", value, "geometria");
			return (Criteria) this;
		}

		public Criteria andGeometriaGreaterThan(String value) {
			addCriterion("GEOMETRIA >", value, "geometria");
			return (Criteria) this;
		}

		public Criteria andGeometriaGreaterThanOrEqualTo(String value) {
			addCriterion("GEOMETRIA >=", value, "geometria");
			return (Criteria) this;
		}

		public Criteria andGeometriaLessThan(String value) {
			addCriterion("GEOMETRIA <", value, "geometria");
			return (Criteria) this;
		}

		public Criteria andGeometriaLessThanOrEqualTo(String value) {
			addCriterion("GEOMETRIA <=", value, "geometria");
			return (Criteria) this;
		}

		public Criteria andGeometriaLike(String value) {
			addCriterion("GEOMETRIA like", value, "geometria");
			return (Criteria) this;
		}

		public Criteria andGeometriaNotLike(String value) {
			addCriterion("GEOMETRIA not like", value, "geometria");
			return (Criteria) this;
		}

		public Criteria andGeometriaIn(List<String> values) {
			addCriterion("GEOMETRIA in", values, "geometria");
			return (Criteria) this;
		}

		public Criteria andGeometriaNotIn(List<String> values) {
			addCriterion("GEOMETRIA not in", values, "geometria");
			return (Criteria) this;
		}

		public Criteria andGeometriaBetween(String value1, String value2) {
			addCriterion("GEOMETRIA between", value1, value2, "geometria");
			return (Criteria) this;
		}

		public Criteria andGeometriaNotBetween(String value1, String value2) {
			addCriterion("GEOMETRIA not between", value1, value2, "geometria");
			return (Criteria) this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("NOMBRE is null");
			return (Criteria) this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("NOMBRE is not null");
			return (Criteria) this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("NOMBRE =", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("NOMBRE <>", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("NOMBRE >", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("NOMBRE >=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("NOMBRE <", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("NOMBRE <=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("NOMBRE like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("NOMBRE not like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreIn(List<String> values) {
			addCriterion("NOMBRE in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotIn(List<String> values) {
			addCriterion("NOMBRE not in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("NOMBRE between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("NOMBRE not between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreViaIsNull() {
			addCriterion("NOMBRE_VIA is null");
			return (Criteria) this;
		}

		public Criteria andNombreViaIsNotNull() {
			addCriterion("NOMBRE_VIA is not null");
			return (Criteria) this;
		}

		public Criteria andNombreViaEqualTo(String value) {
			addCriterion("NOMBRE_VIA =", value, "nombreVia");
			return (Criteria) this;
		}

		public Criteria andNombreViaNotEqualTo(String value) {
			addCriterion("NOMBRE_VIA <>", value, "nombreVia");
			return (Criteria) this;
		}

		public Criteria andNombreViaGreaterThan(String value) {
			addCriterion("NOMBRE_VIA >", value, "nombreVia");
			return (Criteria) this;
		}

		public Criteria andNombreViaGreaterThanOrEqualTo(String value) {
			addCriterion("NOMBRE_VIA >=", value, "nombreVia");
			return (Criteria) this;
		}

		public Criteria andNombreViaLessThan(String value) {
			addCriterion("NOMBRE_VIA <", value, "nombreVia");
			return (Criteria) this;
		}

		public Criteria andNombreViaLessThanOrEqualTo(String value) {
			addCriterion("NOMBRE_VIA <=", value, "nombreVia");
			return (Criteria) this;
		}

		public Criteria andNombreViaLike(String value) {
			addCriterion("NOMBRE_VIA like", value, "nombreVia");
			return (Criteria) this;
		}

		public Criteria andNombreViaNotLike(String value) {
			addCriterion("NOMBRE_VIA not like", value, "nombreVia");
			return (Criteria) this;
		}

		public Criteria andNombreViaIn(List<String> values) {
			addCriterion("NOMBRE_VIA in", values, "nombreVia");
			return (Criteria) this;
		}

		public Criteria andNombreViaNotIn(List<String> values) {
			addCriterion("NOMBRE_VIA not in", values, "nombreVia");
			return (Criteria) this;
		}

		public Criteria andNombreViaBetween(String value1, String value2) {
			addCriterion("NOMBRE_VIA between", value1, value2, "nombreVia");
			return (Criteria) this;
		}

		public Criteria andNombreViaNotBetween(String value1, String value2) {
			addCriterion("NOMBRE_VIA not between", value1, value2, "nombreVia");
			return (Criteria) this;
		}

		public Criteria andNumeroIsNull() {
			addCriterion("NUMERO is null");
			return (Criteria) this;
		}

		public Criteria andNumeroIsNotNull() {
			addCriterion("NUMERO is not null");
			return (Criteria) this;
		}

		public Criteria andNumeroEqualTo(String value) {
			addCriterion("NUMERO =", value, "numero");
			return (Criteria) this;
		}

		public Criteria andNumeroNotEqualTo(String value) {
			addCriterion("NUMERO <>", value, "numero");
			return (Criteria) this;
		}

		public Criteria andNumeroGreaterThan(String value) {
			addCriterion("NUMERO >", value, "numero");
			return (Criteria) this;
		}

		public Criteria andNumeroGreaterThanOrEqualTo(String value) {
			addCriterion("NUMERO >=", value, "numero");
			return (Criteria) this;
		}

		public Criteria andNumeroLessThan(String value) {
			addCriterion("NUMERO <", value, "numero");
			return (Criteria) this;
		}

		public Criteria andNumeroLessThanOrEqualTo(String value) {
			addCriterion("NUMERO <=", value, "numero");
			return (Criteria) this;
		}

		public Criteria andNumeroLike(String value) {
			addCriterion("NUMERO like", value, "numero");
			return (Criteria) this;
		}

		public Criteria andNumeroNotLike(String value) {
			addCriterion("NUMERO not like", value, "numero");
			return (Criteria) this;
		}

		public Criteria andNumeroIn(List<String> values) {
			addCriterion("NUMERO in", values, "numero");
			return (Criteria) this;
		}

		public Criteria andNumeroNotIn(List<String> values) {
			addCriterion("NUMERO not in", values, "numero");
			return (Criteria) this;
		}

		public Criteria andNumeroBetween(String value1, String value2) {
			addCriterion("NUMERO between", value1, value2, "numero");
			return (Criteria) this;
		}

		public Criteria andNumeroNotBetween(String value1, String value2) {
			addCriterion("NUMERO not between", value1, value2, "numero");
			return (Criteria) this;
		}

		public Criteria andLetraIsNull() {
			addCriterion("LETRA is null");
			return (Criteria) this;
		}

		public Criteria andLetraIsNotNull() {
			addCriterion("LETRA is not null");
			return (Criteria) this;
		}

		public Criteria andLetraEqualTo(String value) {
			addCriterion("LETRA =", value, "letra");
			return (Criteria) this;
		}

		public Criteria andLetraNotEqualTo(String value) {
			addCriterion("LETRA <>", value, "letra");
			return (Criteria) this;
		}

		public Criteria andLetraGreaterThan(String value) {
			addCriterion("LETRA >", value, "letra");
			return (Criteria) this;
		}

		public Criteria andLetraGreaterThanOrEqualTo(String value) {
			addCriterion("LETRA >=", value, "letra");
			return (Criteria) this;
		}

		public Criteria andLetraLessThan(String value) {
			addCriterion("LETRA <", value, "letra");
			return (Criteria) this;
		}

		public Criteria andLetraLessThanOrEqualTo(String value) {
			addCriterion("LETRA <=", value, "letra");
			return (Criteria) this;
		}

		public Criteria andLetraLike(String value) {
			addCriterion("LETRA like", value, "letra");
			return (Criteria) this;
		}

		public Criteria andLetraNotLike(String value) {
			addCriterion("LETRA not like", value, "letra");
			return (Criteria) this;
		}

		public Criteria andLetraIn(List<String> values) {
			addCriterion("LETRA in", values, "letra");
			return (Criteria) this;
		}

		public Criteria andLetraNotIn(List<String> values) {
			addCriterion("LETRA not in", values, "letra");
			return (Criteria) this;
		}

		public Criteria andLetraBetween(String value1, String value2) {
			addCriterion("LETRA between", value1, value2, "letra");
			return (Criteria) this;
		}

		public Criteria andLetraNotBetween(String value1, String value2) {
			addCriterion("LETRA not between", value1, value2, "letra");
			return (Criteria) this;
		}

		public Criteria andInteriorIsNull() {
			addCriterion("INTERIOR is null");
			return (Criteria) this;
		}

		public Criteria andInteriorIsNotNull() {
			addCriterion("INTERIOR is not null");
			return (Criteria) this;
		}

		public Criteria andInteriorEqualTo(String value) {
			addCriterion("INTERIOR =", value, "interior");
			return (Criteria) this;
		}

		public Criteria andInteriorNotEqualTo(String value) {
			addCriterion("INTERIOR <>", value, "interior");
			return (Criteria) this;
		}

		public Criteria andInteriorGreaterThan(String value) {
			addCriterion("INTERIOR >", value, "interior");
			return (Criteria) this;
		}

		public Criteria andInteriorGreaterThanOrEqualTo(String value) {
			addCriterion("INTERIOR >=", value, "interior");
			return (Criteria) this;
		}

		public Criteria andInteriorLessThan(String value) {
			addCriterion("INTERIOR <", value, "interior");
			return (Criteria) this;
		}

		public Criteria andInteriorLessThanOrEqualTo(String value) {
			addCriterion("INTERIOR <=", value, "interior");
			return (Criteria) this;
		}

		public Criteria andInteriorLike(String value) {
			addCriterion("INTERIOR like", value, "interior");
			return (Criteria) this;
		}

		public Criteria andInteriorNotLike(String value) {
			addCriterion("INTERIOR not like", value, "interior");
			return (Criteria) this;
		}

		public Criteria andInteriorIn(List<String> values) {
			addCriterion("INTERIOR in", values, "interior");
			return (Criteria) this;
		}

		public Criteria andInteriorNotIn(List<String> values) {
			addCriterion("INTERIOR not in", values, "interior");
			return (Criteria) this;
		}

		public Criteria andInteriorBetween(String value1, String value2) {
			addCriterion("INTERIOR between", value1, value2, "interior");
			return (Criteria) this;
		}

		public Criteria andInteriorNotBetween(String value1, String value2) {
			addCriterion("INTERIOR not between", value1, value2, "interior");
			return (Criteria) this;
		}

		public Criteria andGiroIsNull() {
			addCriterion("GIRO is null");
			return (Criteria) this;
		}

		public Criteria andGiroIsNotNull() {
			addCriterion("GIRO is not null");
			return (Criteria) this;
		}

		public Criteria andGiroEqualTo(String value) {
			addCriterion("GIRO =", value, "giro");
			return (Criteria) this;
		}

		public Criteria andGiroNotEqualTo(String value) {
			addCriterion("GIRO <>", value, "giro");
			return (Criteria) this;
		}

		public Criteria andGiroGreaterThan(String value) {
			addCriterion("GIRO >", value, "giro");
			return (Criteria) this;
		}

		public Criteria andGiroGreaterThanOrEqualTo(String value) {
			addCriterion("GIRO >=", value, "giro");
			return (Criteria) this;
		}

		public Criteria andGiroLessThan(String value) {
			addCriterion("GIRO <", value, "giro");
			return (Criteria) this;
		}

		public Criteria andGiroLessThanOrEqualTo(String value) {
			addCriterion("GIRO <=", value, "giro");
			return (Criteria) this;
		}

		public Criteria andGiroLike(String value) {
			addCriterion("GIRO like", value, "giro");
			return (Criteria) this;
		}

		public Criteria andGiroNotLike(String value) {
			addCriterion("GIRO not like", value, "giro");
			return (Criteria) this;
		}

		public Criteria andGiroIn(List<String> values) {
			addCriterion("GIRO in", values, "giro");
			return (Criteria) this;
		}

		public Criteria andGiroNotIn(List<String> values) {
			addCriterion("GIRO not in", values, "giro");
			return (Criteria) this;
		}

		public Criteria andGiroBetween(String value1, String value2) {
			addCriterion("GIRO between", value1, value2, "giro");
			return (Criteria) this;
		}

		public Criteria andGiroNotBetween(String value1, String value2) {
			addCriterion("GIRO not between", value1, value2, "giro");
			return (Criteria) this;
		}

		public Criteria andPublicoIsNull() {
			addCriterion("PUBLICO is null");
			return (Criteria) this;
		}

		public Criteria andPublicoIsNotNull() {
			addCriterion("PUBLICO is not null");
			return (Criteria) this;
		}

		public Criteria andPublicoEqualTo(String value) {
			addCriterion("PUBLICO =", value, "publico");
			return (Criteria) this;
		}

		public Criteria andPublicoNotEqualTo(String value) {
			addCriterion("PUBLICO <>", value, "publico");
			return (Criteria) this;
		}

		public Criteria andPublicoGreaterThan(String value) {
			addCriterion("PUBLICO >", value, "publico");
			return (Criteria) this;
		}

		public Criteria andPublicoGreaterThanOrEqualTo(String value) {
			addCriterion("PUBLICO >=", value, "publico");
			return (Criteria) this;
		}

		public Criteria andPublicoLessThan(String value) {
			addCriterion("PUBLICO <", value, "publico");
			return (Criteria) this;
		}

		public Criteria andPublicoLessThanOrEqualTo(String value) {
			addCriterion("PUBLICO <=", value, "publico");
			return (Criteria) this;
		}

		public Criteria andPublicoLike(String value) {
			addCriterion("PUBLICO like", value, "publico");
			return (Criteria) this;
		}

		public Criteria andPublicoNotLike(String value) {
			addCriterion("PUBLICO not like", value, "publico");
			return (Criteria) this;
		}

		public Criteria andPublicoIn(List<String> values) {
			addCriterion("PUBLICO in", values, "publico");
			return (Criteria) this;
		}

		public Criteria andPublicoNotIn(List<String> values) {
			addCriterion("PUBLICO not in", values, "publico");
			return (Criteria) this;
		}

		public Criteria andPublicoBetween(String value1, String value2) {
			addCriterion("PUBLICO between", value1, value2, "publico");
			return (Criteria) this;
		}

		public Criteria andPublicoNotBetween(String value1, String value2) {
			addCriterion("PUBLICO not between", value1, value2, "publico");
			return (Criteria) this;
		}

		public Criteria andZonaIsNull() {
			addCriterion("ZONA is null");
			return (Criteria) this;
		}

		public Criteria andZonaIsNotNull() {
			addCriterion("ZONA is not null");
			return (Criteria) this;
		}

		public Criteria andZonaEqualTo(String value) {
			addCriterion("ZONA =", value, "zona");
			return (Criteria) this;
		}

		public Criteria andZonaNotEqualTo(String value) {
			addCriterion("ZONA <>", value, "zona");
			return (Criteria) this;
		}

		public Criteria andZonaGreaterThan(String value) {
			addCriterion("ZONA >", value, "zona");
			return (Criteria) this;
		}

		public Criteria andZonaGreaterThanOrEqualTo(String value) {
			addCriterion("ZONA >=", value, "zona");
			return (Criteria) this;
		}

		public Criteria andZonaLessThan(String value) {
			addCriterion("ZONA <", value, "zona");
			return (Criteria) this;
		}

		public Criteria andZonaLessThanOrEqualTo(String value) {
			addCriterion("ZONA <=", value, "zona");
			return (Criteria) this;
		}

		public Criteria andZonaLike(String value) {
			addCriterion("ZONA like", value, "zona");
			return (Criteria) this;
		}

		public Criteria andZonaNotLike(String value) {
			addCriterion("ZONA not like", value, "zona");
			return (Criteria) this;
		}

		public Criteria andZonaIn(List<String> values) {
			addCriterion("ZONA in", values, "zona");
			return (Criteria) this;
		}

		public Criteria andZonaNotIn(List<String> values) {
			addCriterion("ZONA not in", values, "zona");
			return (Criteria) this;
		}

		public Criteria andZonaBetween(String value1, String value2) {
			addCriterion("ZONA between", value1, value2, "zona");
			return (Criteria) this;
		}

		public Criteria andZonaNotBetween(String value1, String value2) {
			addCriterion("ZONA not between", value1, value2, "zona");
			return (Criteria) this;
		}

		public Criteria andTipoIsNull() {
			addCriterion("TIPO is null");
			return (Criteria) this;
		}

		public Criteria andTipoIsNotNull() {
			addCriterion("TIPO is not null");
			return (Criteria) this;
		}

		public Criteria andTipoEqualTo(Integer value) {
			addCriterion("TIPO =", value, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoNotEqualTo(Integer value) {
			addCriterion("TIPO <>", value, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoGreaterThan(Integer value) {
			addCriterion("TIPO >", value, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoGreaterThanOrEqualTo(Integer value) {
			addCriterion("TIPO >=", value, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoLessThan(Integer value) {
			addCriterion("TIPO <", value, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoLessThanOrEqualTo(Integer value) {
			addCriterion("TIPO <=", value, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoIn(List<Integer> values) {
			addCriterion("TIPO in", values, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoNotIn(List<Integer> values) {
			addCriterion("TIPO not in", values, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoBetween(Integer value1, Integer value2) {
			addCriterion("TIPO between", value1, value2, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoNotBetween(Integer value1, Integer value2) {
			addCriterion("TIPO not between", value1, value2, "tipo");
			return (Criteria) this;
		}

		public Criteria andPuntoIniIsNull() {
			addCriterion("PUNTO_INI is null");
			return (Criteria) this;
		}

		public Criteria andPuntoIniIsNotNull() {
			addCriterion("PUNTO_INI is not null");
			return (Criteria) this;
		}

		public Criteria andPuntoIniEqualTo(String value) {
			addCriterion("PUNTO_INI =", value, "puntoIni");
			return (Criteria) this;
		}

		public Criteria andPuntoIniNotEqualTo(String value) {
			addCriterion("PUNTO_INI <>", value, "puntoIni");
			return (Criteria) this;
		}

		public Criteria andPuntoIniGreaterThan(String value) {
			addCriterion("PUNTO_INI >", value, "puntoIni");
			return (Criteria) this;
		}

		public Criteria andPuntoIniGreaterThanOrEqualTo(String value) {
			addCriterion("PUNTO_INI >=", value, "puntoIni");
			return (Criteria) this;
		}

		public Criteria andPuntoIniLessThan(String value) {
			addCriterion("PUNTO_INI <", value, "puntoIni");
			return (Criteria) this;
		}

		public Criteria andPuntoIniLessThanOrEqualTo(String value) {
			addCriterion("PUNTO_INI <=", value, "puntoIni");
			return (Criteria) this;
		}

		public Criteria andPuntoIniLike(String value) {
			addCriterion("PUNTO_INI like", value, "puntoIni");
			return (Criteria) this;
		}

		public Criteria andPuntoIniNotLike(String value) {
			addCriterion("PUNTO_INI not like", value, "puntoIni");
			return (Criteria) this;
		}

		public Criteria andPuntoIniIn(List<String> values) {
			addCriterion("PUNTO_INI in", values, "puntoIni");
			return (Criteria) this;
		}

		public Criteria andPuntoIniNotIn(List<String> values) {
			addCriterion("PUNTO_INI not in", values, "puntoIni");
			return (Criteria) this;
		}

		public Criteria andPuntoIniBetween(String value1, String value2) {
			addCriterion("PUNTO_INI between", value1, value2, "puntoIni");
			return (Criteria) this;
		}

		public Criteria andPuntoIniNotBetween(String value1, String value2) {
			addCriterion("PUNTO_INI not between", value1, value2, "puntoIni");
			return (Criteria) this;
		}

		public Criteria andPuntoFinIsNull() {
			addCriterion("PUNTO_FIN is null");
			return (Criteria) this;
		}

		public Criteria andPuntoFinIsNotNull() {
			addCriterion("PUNTO_FIN is not null");
			return (Criteria) this;
		}

		public Criteria andPuntoFinEqualTo(String value) {
			addCriterion("PUNTO_FIN =", value, "puntoFin");
			return (Criteria) this;
		}

		public Criteria andPuntoFinNotEqualTo(String value) {
			addCriterion("PUNTO_FIN <>", value, "puntoFin");
			return (Criteria) this;
		}

		public Criteria andPuntoFinGreaterThan(String value) {
			addCriterion("PUNTO_FIN >", value, "puntoFin");
			return (Criteria) this;
		}

		public Criteria andPuntoFinGreaterThanOrEqualTo(String value) {
			addCriterion("PUNTO_FIN >=", value, "puntoFin");
			return (Criteria) this;
		}

		public Criteria andPuntoFinLessThan(String value) {
			addCriterion("PUNTO_FIN <", value, "puntoFin");
			return (Criteria) this;
		}

		public Criteria andPuntoFinLessThanOrEqualTo(String value) {
			addCriterion("PUNTO_FIN <=", value, "puntoFin");
			return (Criteria) this;
		}

		public Criteria andPuntoFinLike(String value) {
			addCriterion("PUNTO_FIN like", value, "puntoFin");
			return (Criteria) this;
		}

		public Criteria andPuntoFinNotLike(String value) {
			addCriterion("PUNTO_FIN not like", value, "puntoFin");
			return (Criteria) this;
		}

		public Criteria andPuntoFinIn(List<String> values) {
			addCriterion("PUNTO_FIN in", values, "puntoFin");
			return (Criteria) this;
		}

		public Criteria andPuntoFinNotIn(List<String> values) {
			addCriterion("PUNTO_FIN not in", values, "puntoFin");
			return (Criteria) this;
		}

		public Criteria andPuntoFinBetween(String value1, String value2) {
			addCriterion("PUNTO_FIN between", value1, value2, "puntoFin");
			return (Criteria) this;
		}

		public Criteria andPuntoFinNotBetween(String value1, String value2) {
			addCriterion("PUNTO_FIN not between", value1, value2, "puntoFin");
			return (Criteria) this;
		}

		public Criteria andTramoIsNull() {
			addCriterion("TRAMO is null");
			return (Criteria) this;
		}

		public Criteria andTramoIsNotNull() {
			addCriterion("TRAMO is not null");
			return (Criteria) this;
		}

		public Criteria andTramoEqualTo(String value) {
			addCriterion("TRAMO =", value, "tramo");
			return (Criteria) this;
		}

		public Criteria andTramoNotEqualTo(String value) {
			addCriterion("TRAMO <>", value, "tramo");
			return (Criteria) this;
		}

		public Criteria andTramoGreaterThan(String value) {
			addCriterion("TRAMO >", value, "tramo");
			return (Criteria) this;
		}

		public Criteria andTramoGreaterThanOrEqualTo(String value) {
			addCriterion("TRAMO >=", value, "tramo");
			return (Criteria) this;
		}

		public Criteria andTramoLessThan(String value) {
			addCriterion("TRAMO <", value, "tramo");
			return (Criteria) this;
		}

		public Criteria andTramoLessThanOrEqualTo(String value) {
			addCriterion("TRAMO <=", value, "tramo");
			return (Criteria) this;
		}

		public Criteria andTramoLike(String value) {
			addCriterion("TRAMO like", value, "tramo");
			return (Criteria) this;
		}

		public Criteria andTramoNotLike(String value) {
			addCriterion("TRAMO not like", value, "tramo");
			return (Criteria) this;
		}

		public Criteria andTramoIn(List<String> values) {
			addCriterion("TRAMO in", values, "tramo");
			return (Criteria) this;
		}

		public Criteria andTramoNotIn(List<String> values) {
			addCriterion("TRAMO not in", values, "tramo");
			return (Criteria) this;
		}

		public Criteria andTramoBetween(String value1, String value2) {
			addCriterion("TRAMO between", value1, value2, "tramo");
			return (Criteria) this;
		}

		public Criteria andTramoNotBetween(String value1, String value2) {
			addCriterion("TRAMO not between", value1, value2, "tramo");
			return (Criteria) this;
		}

		public Criteria andViaIniIsNull() {
			addCriterion("VIA_INI is null");
			return (Criteria) this;
		}

		public Criteria andViaIniIsNotNull() {
			addCriterion("VIA_INI is not null");
			return (Criteria) this;
		}

		public Criteria andViaIniEqualTo(String value) {
			addCriterion("VIA_INI =", value, "viaIni");
			return (Criteria) this;
		}

		public Criteria andViaIniNotEqualTo(String value) {
			addCriterion("VIA_INI <>", value, "viaIni");
			return (Criteria) this;
		}

		public Criteria andViaIniGreaterThan(String value) {
			addCriterion("VIA_INI >", value, "viaIni");
			return (Criteria) this;
		}

		public Criteria andViaIniGreaterThanOrEqualTo(String value) {
			addCriterion("VIA_INI >=", value, "viaIni");
			return (Criteria) this;
		}

		public Criteria andViaIniLessThan(String value) {
			addCriterion("VIA_INI <", value, "viaIni");
			return (Criteria) this;
		}

		public Criteria andViaIniLessThanOrEqualTo(String value) {
			addCriterion("VIA_INI <=", value, "viaIni");
			return (Criteria) this;
		}

		public Criteria andViaIniLike(String value) {
			addCriterion("VIA_INI like", value, "viaIni");
			return (Criteria) this;
		}

		public Criteria andViaIniNotLike(String value) {
			addCriterion("VIA_INI not like", value, "viaIni");
			return (Criteria) this;
		}

		public Criteria andViaIniIn(List<String> values) {
			addCriterion("VIA_INI in", values, "viaIni");
			return (Criteria) this;
		}

		public Criteria andViaIniNotIn(List<String> values) {
			addCriterion("VIA_INI not in", values, "viaIni");
			return (Criteria) this;
		}

		public Criteria andViaIniBetween(String value1, String value2) {
			addCriterion("VIA_INI between", value1, value2, "viaIni");
			return (Criteria) this;
		}

		public Criteria andViaIniNotBetween(String value1, String value2) {
			addCriterion("VIA_INI not between", value1, value2, "viaIni");
			return (Criteria) this;
		}

		public Criteria andViaFinIsNull() {
			addCriterion("VIA_FIN is null");
			return (Criteria) this;
		}

		public Criteria andViaFinIsNotNull() {
			addCriterion("VIA_FIN is not null");
			return (Criteria) this;
		}

		public Criteria andViaFinEqualTo(String value) {
			addCriterion("VIA_FIN =", value, "viaFin");
			return (Criteria) this;
		}

		public Criteria andViaFinNotEqualTo(String value) {
			addCriterion("VIA_FIN <>", value, "viaFin");
			return (Criteria) this;
		}

		public Criteria andViaFinGreaterThan(String value) {
			addCriterion("VIA_FIN >", value, "viaFin");
			return (Criteria) this;
		}

		public Criteria andViaFinGreaterThanOrEqualTo(String value) {
			addCriterion("VIA_FIN >=", value, "viaFin");
			return (Criteria) this;
		}

		public Criteria andViaFinLessThan(String value) {
			addCriterion("VIA_FIN <", value, "viaFin");
			return (Criteria) this;
		}

		public Criteria andViaFinLessThanOrEqualTo(String value) {
			addCriterion("VIA_FIN <=", value, "viaFin");
			return (Criteria) this;
		}

		public Criteria andViaFinLike(String value) {
			addCriterion("VIA_FIN like", value, "viaFin");
			return (Criteria) this;
		}

		public Criteria andViaFinNotLike(String value) {
			addCriterion("VIA_FIN not like", value, "viaFin");
			return (Criteria) this;
		}

		public Criteria andViaFinIn(List<String> values) {
			addCriterion("VIA_FIN in", values, "viaFin");
			return (Criteria) this;
		}

		public Criteria andViaFinNotIn(List<String> values) {
			addCriterion("VIA_FIN not in", values, "viaFin");
			return (Criteria) this;
		}

		public Criteria andViaFinBetween(String value1, String value2) {
			addCriterion("VIA_FIN between", value1, value2, "viaFin");
			return (Criteria) this;
		}

		public Criteria andViaFinNotBetween(String value1, String value2) {
			addCriterion("VIA_FIN not between", value1, value2, "viaFin");
			return (Criteria) this;
		}

		public Criteria andSentidoIsNull() {
			addCriterion("SENTIDO is null");
			return (Criteria) this;
		}

		public Criteria andSentidoIsNotNull() {
			addCriterion("SENTIDO is not null");
			return (Criteria) this;
		}

		public Criteria andSentidoEqualTo(String value) {
			addCriterion("SENTIDO =", value, "sentido");
			return (Criteria) this;
		}

		public Criteria andSentidoNotEqualTo(String value) {
			addCriterion("SENTIDO <>", value, "sentido");
			return (Criteria) this;
		}

		public Criteria andSentidoGreaterThan(String value) {
			addCriterion("SENTIDO >", value, "sentido");
			return (Criteria) this;
		}

		public Criteria andSentidoGreaterThanOrEqualTo(String value) {
			addCriterion("SENTIDO >=", value, "sentido");
			return (Criteria) this;
		}

		public Criteria andSentidoLessThan(String value) {
			addCriterion("SENTIDO <", value, "sentido");
			return (Criteria) this;
		}

		public Criteria andSentidoLessThanOrEqualTo(String value) {
			addCriterion("SENTIDO <=", value, "sentido");
			return (Criteria) this;
		}

		public Criteria andSentidoLike(String value) {
			addCriterion("SENTIDO like", value, "sentido");
			return (Criteria) this;
		}

		public Criteria andSentidoNotLike(String value) {
			addCriterion("SENTIDO not like", value, "sentido");
			return (Criteria) this;
		}

		public Criteria andSentidoIn(List<String> values) {
			addCriterion("SENTIDO in", values, "sentido");
			return (Criteria) this;
		}

		public Criteria andSentidoNotIn(List<String> values) {
			addCriterion("SENTIDO not in", values, "sentido");
			return (Criteria) this;
		}

		public Criteria andSentidoBetween(String value1, String value2) {
			addCriterion("SENTIDO between", value1, value2, "sentido");
			return (Criteria) this;
		}

		public Criteria andSentidoNotBetween(String value1, String value2) {
			addCriterion("SENTIDO not between", value1, value2, "sentido");
			return (Criteria) this;
		}

		public Criteria andPercentilIsNull() {
			addCriterion("PERCENTIL is null");
			return (Criteria) this;
		}

		public Criteria andPercentilIsNotNull() {
			addCriterion("PERCENTIL is not null");
			return (Criteria) this;
		}

		public Criteria andPercentilEqualTo(String value) {
			addCriterion("PERCENTIL =", value, "percentil");
			return (Criteria) this;
		}

		public Criteria andPercentilNotEqualTo(String value) {
			addCriterion("PERCENTIL <>", value, "percentil");
			return (Criteria) this;
		}

		public Criteria andPercentilGreaterThan(String value) {
			addCriterion("PERCENTIL >", value, "percentil");
			return (Criteria) this;
		}

		public Criteria andPercentilGreaterThanOrEqualTo(String value) {
			addCriterion("PERCENTIL >=", value, "percentil");
			return (Criteria) this;
		}

		public Criteria andPercentilLessThan(String value) {
			addCriterion("PERCENTIL <", value, "percentil");
			return (Criteria) this;
		}

		public Criteria andPercentilLessThanOrEqualTo(String value) {
			addCriterion("PERCENTIL <=", value, "percentil");
			return (Criteria) this;
		}

		public Criteria andPercentilLike(String value) {
			addCriterion("PERCENTIL like", value, "percentil");
			return (Criteria) this;
		}

		public Criteria andPercentilNotLike(String value) {
			addCriterion("PERCENTIL not like", value, "percentil");
			return (Criteria) this;
		}

		public Criteria andPercentilIn(List<String> values) {
			addCriterion("PERCENTIL in", values, "percentil");
			return (Criteria) this;
		}

		public Criteria andPercentilNotIn(List<String> values) {
			addCriterion("PERCENTIL not in", values, "percentil");
			return (Criteria) this;
		}

		public Criteria andPercentilBetween(String value1, String value2) {
			addCriterion("PERCENTIL between", value1, value2, "percentil");
			return (Criteria) this;
		}

		public Criteria andPercentilNotBetween(String value1, String value2) {
			addCriterion("PERCENTIL not between", value1, value2, "percentil");
			return (Criteria) this;
		}

		public Criteria andLimiteIsNull() {
			addCriterion("LIMITE is null");
			return (Criteria) this;
		}

		public Criteria andLimiteIsNotNull() {
			addCriterion("LIMITE is not null");
			return (Criteria) this;
		}

		public Criteria andLimiteEqualTo(String value) {
			addCriterion("LIMITE =", value, "limite");
			return (Criteria) this;
		}

		public Criteria andLimiteNotEqualTo(String value) {
			addCriterion("LIMITE <>", value, "limite");
			return (Criteria) this;
		}

		public Criteria andLimiteGreaterThan(String value) {
			addCriterion("LIMITE >", value, "limite");
			return (Criteria) this;
		}

		public Criteria andLimiteGreaterThanOrEqualTo(String value) {
			addCriterion("LIMITE >=", value, "limite");
			return (Criteria) this;
		}

		public Criteria andLimiteLessThan(String value) {
			addCriterion("LIMITE <", value, "limite");
			return (Criteria) this;
		}

		public Criteria andLimiteLessThanOrEqualTo(String value) {
			addCriterion("LIMITE <=", value, "limite");
			return (Criteria) this;
		}

		public Criteria andLimiteLike(String value) {
			addCriterion("LIMITE like", value, "limite");
			return (Criteria) this;
		}

		public Criteria andLimiteNotLike(String value) {
			addCriterion("LIMITE not like", value, "limite");
			return (Criteria) this;
		}

		public Criteria andLimiteIn(List<String> values) {
			addCriterion("LIMITE in", values, "limite");
			return (Criteria) this;
		}

		public Criteria andLimiteNotIn(List<String> values) {
			addCriterion("LIMITE not in", values, "limite");
			return (Criteria) this;
		}

		public Criteria andLimiteBetween(String value1, String value2) {
			addCriterion("LIMITE between", value1, value2, "limite");
			return (Criteria) this;
		}

		public Criteria andLimiteNotBetween(String value1, String value2) {
			addCriterion("LIMITE not between", value1, value2, "limite");
			return (Criteria) this;
		}

		public Criteria andEspaciosIsNull() {
			addCriterion("ESPACIOS is null");
			return (Criteria) this;
		}

		public Criteria andEspaciosIsNotNull() {
			addCriterion("ESPACIOS is not null");
			return (Criteria) this;
		}

		public Criteria andEspaciosEqualTo(String value) {
			addCriterion("ESPACIOS =", value, "espacios");
			return (Criteria) this;
		}

		public Criteria andEspaciosNotEqualTo(String value) {
			addCriterion("ESPACIOS <>", value, "espacios");
			return (Criteria) this;
		}

		public Criteria andEspaciosGreaterThan(String value) {
			addCriterion("ESPACIOS >", value, "espacios");
			return (Criteria) this;
		}

		public Criteria andEspaciosGreaterThanOrEqualTo(String value) {
			addCriterion("ESPACIOS >=", value, "espacios");
			return (Criteria) this;
		}

		public Criteria andEspaciosLessThan(String value) {
			addCriterion("ESPACIOS <", value, "espacios");
			return (Criteria) this;
		}

		public Criteria andEspaciosLessThanOrEqualTo(String value) {
			addCriterion("ESPACIOS <=", value, "espacios");
			return (Criteria) this;
		}

		public Criteria andEspaciosLike(String value) {
			addCriterion("ESPACIOS like", value, "espacios");
			return (Criteria) this;
		}

		public Criteria andEspaciosNotLike(String value) {
			addCriterion("ESPACIOS not like", value, "espacios");
			return (Criteria) this;
		}

		public Criteria andEspaciosIn(List<String> values) {
			addCriterion("ESPACIOS in", values, "espacios");
			return (Criteria) this;
		}

		public Criteria andEspaciosNotIn(List<String> values) {
			addCriterion("ESPACIOS not in", values, "espacios");
			return (Criteria) this;
		}

		public Criteria andEspaciosBetween(String value1, String value2) {
			addCriterion("ESPACIOS between", value1, value2, "espacios");
			return (Criteria) this;
		}

		public Criteria andEspaciosNotBetween(String value1, String value2) {
			addCriterion("ESPACIOS not between", value1, value2, "espacios");
			return (Criteria) this;
		}

		public Criteria andSectorIsNull() {
			addCriterion("SECTOR is null");
			return (Criteria) this;
		}

		public Criteria andSectorIsNotNull() {
			addCriterion("SECTOR is not null");
			return (Criteria) this;
		}

		public Criteria andSectorEqualTo(String value) {
			addCriterion("SECTOR =", value, "sector");
			return (Criteria) this;
		}

		public Criteria andSectorNotEqualTo(String value) {
			addCriterion("SECTOR <>", value, "sector");
			return (Criteria) this;
		}

		public Criteria andSectorGreaterThan(String value) {
			addCriterion("SECTOR >", value, "sector");
			return (Criteria) this;
		}

		public Criteria andSectorGreaterThanOrEqualTo(String value) {
			addCriterion("SECTOR >=", value, "sector");
			return (Criteria) this;
		}

		public Criteria andSectorLessThan(String value) {
			addCriterion("SECTOR <", value, "sector");
			return (Criteria) this;
		}

		public Criteria andSectorLessThanOrEqualTo(String value) {
			addCriterion("SECTOR <=", value, "sector");
			return (Criteria) this;
		}

		public Criteria andSectorLike(String value) {
			addCriterion("SECTOR like", value, "sector");
			return (Criteria) this;
		}

		public Criteria andSectorNotLike(String value) {
			addCriterion("SECTOR not like", value, "sector");
			return (Criteria) this;
		}

		public Criteria andSectorIn(List<String> values) {
			addCriterion("SECTOR in", values, "sector");
			return (Criteria) this;
		}

		public Criteria andSectorNotIn(List<String> values) {
			addCriterion("SECTOR not in", values, "sector");
			return (Criteria) this;
		}

		public Criteria andSectorBetween(String value1, String value2) {
			addCriterion("SECTOR between", value1, value2, "sector");
			return (Criteria) this;
		}

		public Criteria andSectorNotBetween(String value1, String value2) {
			addCriterion("SECTOR not between", value1, value2, "sector");
			return (Criteria) this;
		}

		public Criteria andCuadraIsNull() {
			addCriterion("CUADRA is null");
			return (Criteria) this;
		}

		public Criteria andCuadraIsNotNull() {
			addCriterion("CUADRA is not null");
			return (Criteria) this;
		}

		public Criteria andCuadraEqualTo(String value) {
			addCriterion("CUADRA =", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraNotEqualTo(String value) {
			addCriterion("CUADRA <>", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraGreaterThan(String value) {
			addCriterion("CUADRA >", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraGreaterThanOrEqualTo(String value) {
			addCriterion("CUADRA >=", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraLessThan(String value) {
			addCriterion("CUADRA <", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraLessThanOrEqualTo(String value) {
			addCriterion("CUADRA <=", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraLike(String value) {
			addCriterion("CUADRA like", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraNotLike(String value) {
			addCriterion("CUADRA not like", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraIn(List<String> values) {
			addCriterion("CUADRA in", values, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraNotIn(List<String> values) {
			addCriterion("CUADRA not in", values, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraBetween(String value1, String value2) {
			addCriterion("CUADRA between", value1, value2, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraNotBetween(String value1, String value2) {
			addCriterion("CUADRA not between", value1, value2, "cuadra");
			return (Criteria) this;
		}

		public Criteria andLadoIsNull() {
			addCriterion("LADO is null");
			return (Criteria) this;
		}

		public Criteria andLadoIsNotNull() {
			addCriterion("LADO is not null");
			return (Criteria) this;
		}

		public Criteria andLadoEqualTo(String value) {
			addCriterion("LADO =", value, "lado");
			return (Criteria) this;
		}

		public Criteria andLadoNotEqualTo(String value) {
			addCriterion("LADO <>", value, "lado");
			return (Criteria) this;
		}

		public Criteria andLadoGreaterThan(String value) {
			addCriterion("LADO >", value, "lado");
			return (Criteria) this;
		}

		public Criteria andLadoGreaterThanOrEqualTo(String value) {
			addCriterion("LADO >=", value, "lado");
			return (Criteria) this;
		}

		public Criteria andLadoLessThan(String value) {
			addCriterion("LADO <", value, "lado");
			return (Criteria) this;
		}

		public Criteria andLadoLessThanOrEqualTo(String value) {
			addCriterion("LADO <=", value, "lado");
			return (Criteria) this;
		}

		public Criteria andLadoLike(String value) {
			addCriterion("LADO like", value, "lado");
			return (Criteria) this;
		}

		public Criteria andLadoNotLike(String value) {
			addCriterion("LADO not like", value, "lado");
			return (Criteria) this;
		}

		public Criteria andLadoIn(List<String> values) {
			addCriterion("LADO in", values, "lado");
			return (Criteria) this;
		}

		public Criteria andLadoNotIn(List<String> values) {
			addCriterion("LADO not in", values, "lado");
			return (Criteria) this;
		}

		public Criteria andLadoBetween(String value1, String value2) {
			addCriterion("LADO between", value1, value2, "lado");
			return (Criteria) this;
		}

		public Criteria andLadoNotBetween(String value1, String value2) {
			addCriterion("LADO not between", value1, value2, "lado");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioIsNull() {
			addCriterion("HORA_PASO_PROMEDIO is null");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioIsNotNull() {
			addCriterion("HORA_PASO_PROMEDIO is not null");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioEqualTo(String value) {
			addCriterion("HORA_PASO_PROMEDIO =", value, "horaPasoPromedio");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioNotEqualTo(String value) {
			addCriterion("HORA_PASO_PROMEDIO <>", value, "horaPasoPromedio");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioGreaterThan(String value) {
			addCriterion("HORA_PASO_PROMEDIO >", value, "horaPasoPromedio");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioGreaterThanOrEqualTo(String value) {
			addCriterion("HORA_PASO_PROMEDIO >=", value, "horaPasoPromedio");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioLessThan(String value) {
			addCriterion("HORA_PASO_PROMEDIO <", value, "horaPasoPromedio");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioLessThanOrEqualTo(String value) {
			addCriterion("HORA_PASO_PROMEDIO <=", value, "horaPasoPromedio");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioLike(String value) {
			addCriterion("HORA_PASO_PROMEDIO like", value, "horaPasoPromedio");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioNotLike(String value) {
			addCriterion("HORA_PASO_PROMEDIO not like", value, "horaPasoPromedio");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioIn(List<String> values) {
			addCriterion("HORA_PASO_PROMEDIO in", values, "horaPasoPromedio");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioNotIn(List<String> values) {
			addCriterion("HORA_PASO_PROMEDIO not in", values, "horaPasoPromedio");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioBetween(String value1, String value2) {
			addCriterion("HORA_PASO_PROMEDIO between", value1, value2, "horaPasoPromedio");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioNotBetween(String value1, String value2) {
			addCriterion("HORA_PASO_PROMEDIO not between", value1, value2, "horaPasoPromedio");
			return (Criteria) this;
		}

		public Criteria andDetalleIsNull() {
			addCriterion("DETALLE is null");
			return (Criteria) this;
		}

		public Criteria andDetalleIsNotNull() {
			addCriterion("DETALLE is not null");
			return (Criteria) this;
		}

		public Criteria andDetalleEqualTo(String value) {
			addCriterion("DETALLE =", value, "detalle");
			return (Criteria) this;
		}

		public Criteria andDetalleNotEqualTo(String value) {
			addCriterion("DETALLE <>", value, "detalle");
			return (Criteria) this;
		}

		public Criteria andDetalleGreaterThan(String value) {
			addCriterion("DETALLE >", value, "detalle");
			return (Criteria) this;
		}

		public Criteria andDetalleGreaterThanOrEqualTo(String value) {
			addCriterion("DETALLE >=", value, "detalle");
			return (Criteria) this;
		}

		public Criteria andDetalleLessThan(String value) {
			addCriterion("DETALLE <", value, "detalle");
			return (Criteria) this;
		}

		public Criteria andDetalleLessThanOrEqualTo(String value) {
			addCriterion("DETALLE <=", value, "detalle");
			return (Criteria) this;
		}

		public Criteria andDetalleLike(String value) {
			addCriterion("DETALLE like", value, "detalle");
			return (Criteria) this;
		}

		public Criteria andDetalleNotLike(String value) {
			addCriterion("DETALLE not like", value, "detalle");
			return (Criteria) this;
		}

		public Criteria andDetalleIn(List<String> values) {
			addCriterion("DETALLE in", values, "detalle");
			return (Criteria) this;
		}

		public Criteria andDetalleNotIn(List<String> values) {
			addCriterion("DETALLE not in", values, "detalle");
			return (Criteria) this;
		}

		public Criteria andDetalleBetween(String value1, String value2) {
			addCriterion("DETALLE between", value1, value2, "detalle");
			return (Criteria) this;
		}

		public Criteria andDetalleNotBetween(String value1, String value2) {
			addCriterion("DETALLE not between", value1, value2, "detalle");
			return (Criteria) this;
		}

		public Criteria andGeometriaLikeInsensitive(String value) {
			addCriterion("upper(GEOMETRIA) like", value.toUpperCase(), "geometria");
			return (Criteria) this;
		}

		public Criteria andNombreLikeInsensitive(String value) {
			addCriterion("upper(NOMBRE) like", value.toUpperCase(), "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreViaLikeInsensitive(String value) {
			addCriterion("upper(NOMBRE_VIA) like", value.toUpperCase(), "nombreVia");
			return (Criteria) this;
		}

		public Criteria andNumeroLikeInsensitive(String value) {
			addCriterion("upper(NUMERO) like", value.toUpperCase(), "numero");
			return (Criteria) this;
		}

		public Criteria andLetraLikeInsensitive(String value) {
			addCriterion("upper(LETRA) like", value.toUpperCase(), "letra");
			return (Criteria) this;
		}

		public Criteria andInteriorLikeInsensitive(String value) {
			addCriterion("upper(INTERIOR) like", value.toUpperCase(), "interior");
			return (Criteria) this;
		}

		public Criteria andGiroLikeInsensitive(String value) {
			addCriterion("upper(GIRO) like", value.toUpperCase(), "giro");
			return (Criteria) this;
		}

		public Criteria andPublicoLikeInsensitive(String value) {
			addCriterion("upper(PUBLICO) like", value.toUpperCase(), "publico");
			return (Criteria) this;
		}

		public Criteria andZonaLikeInsensitive(String value) {
			addCriterion("upper(ZONA) like", value.toUpperCase(), "zona");
			return (Criteria) this;
		}

		public Criteria andPuntoIniLikeInsensitive(String value) {
			addCriterion("upper(PUNTO_INI) like", value.toUpperCase(), "puntoIni");
			return (Criteria) this;
		}

		public Criteria andPuntoFinLikeInsensitive(String value) {
			addCriterion("upper(PUNTO_FIN) like", value.toUpperCase(), "puntoFin");
			return (Criteria) this;
		}

		public Criteria andTramoLikeInsensitive(String value) {
			addCriterion("upper(TRAMO) like", value.toUpperCase(), "tramo");
			return (Criteria) this;
		}

		public Criteria andViaIniLikeInsensitive(String value) {
			addCriterion("upper(VIA_INI) like", value.toUpperCase(), "viaIni");
			return (Criteria) this;
		}

		public Criteria andViaFinLikeInsensitive(String value) {
			addCriterion("upper(VIA_FIN) like", value.toUpperCase(), "viaFin");
			return (Criteria) this;
		}

		public Criteria andSentidoLikeInsensitive(String value) {
			addCriterion("upper(SENTIDO) like", value.toUpperCase(), "sentido");
			return (Criteria) this;
		}

		public Criteria andPercentilLikeInsensitive(String value) {
			addCriterion("upper(PERCENTIL) like", value.toUpperCase(), "percentil");
			return (Criteria) this;
		}

		public Criteria andLimiteLikeInsensitive(String value) {
			addCriterion("upper(LIMITE) like", value.toUpperCase(), "limite");
			return (Criteria) this;
		}

		public Criteria andEspaciosLikeInsensitive(String value) {
			addCriterion("upper(ESPACIOS) like", value.toUpperCase(), "espacios");
			return (Criteria) this;
		}

		public Criteria andSectorLikeInsensitive(String value) {
			addCriterion("upper(SECTOR) like", value.toUpperCase(), "sector");
			return (Criteria) this;
		}

		public Criteria andCuadraLikeInsensitive(String value) {
			addCriterion("upper(CUADRA) like", value.toUpperCase(), "cuadra");
			return (Criteria) this;
		}

		public Criteria andLadoLikeInsensitive(String value) {
			addCriterion("upper(LADO) like", value.toUpperCase(), "lado");
			return (Criteria) this;
		}

		public Criteria andHoraPasoPromedioLikeInsensitive(String value) {
			addCriterion("upper(HORA_PASO_PROMEDIO) like", value.toUpperCase(), "horaPasoPromedio");
			return (Criteria) this;
		}

		public Criteria andDetalleLikeInsensitive(String value) {
			addCriterion("upper(DETALLE) like", value.toUpperCase(), "detalle");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GEO_MAP_GENERICO
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 01 15:26:24 COT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}