package pe.gob.miraflores.mobile.domain.mapaincidencias;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PreInscripcionCierreCalleCriteria {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public PreInscripcionCierreCalleCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andDireccionIsNull() {
			addCriterion("DIRECCION is null");
			return (Criteria) this;
		}

		public Criteria andDireccionIsNotNull() {
			addCriterion("DIRECCION is not null");
			return (Criteria) this;
		}

		public Criteria andDireccionEqualTo(String value) {
			addCriterion("DIRECCION =", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionNotEqualTo(String value) {
			addCriterion("DIRECCION <>", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionGreaterThan(String value) {
			addCriterion("DIRECCION >", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionGreaterThanOrEqualTo(String value) {
			addCriterion("DIRECCION >=", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionLessThan(String value) {
			addCriterion("DIRECCION <", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionLessThanOrEqualTo(String value) {
			addCriterion("DIRECCION <=", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionLike(String value) {
			addCriterion("DIRECCION like", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionNotLike(String value) {
			addCriterion("DIRECCION not like", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionIn(List<String> values) {
			addCriterion("DIRECCION in", values, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionNotIn(List<String> values) {
			addCriterion("DIRECCION not in", values, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionBetween(String value1, String value2) {
			addCriterion("DIRECCION between", value1, value2, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionNotBetween(String value1, String value2) {
			addCriterion("DIRECCION not between", value1, value2, "direccion");
			return (Criteria) this;
		}

		public Criteria andCuadraIsNull() {
			addCriterion("CUADRA is null");
			return (Criteria) this;
		}

		public Criteria andCuadraIsNotNull() {
			addCriterion("CUADRA is not null");
			return (Criteria) this;
		}

		public Criteria andCuadraEqualTo(String value) {
			addCriterion("CUADRA =", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraNotEqualTo(String value) {
			addCriterion("CUADRA <>", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraGreaterThan(String value) {
			addCriterion("CUADRA >", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraGreaterThanOrEqualTo(String value) {
			addCriterion("CUADRA >=", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraLessThan(String value) {
			addCriterion("CUADRA <", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraLessThanOrEqualTo(String value) {
			addCriterion("CUADRA <=", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraLike(String value) {
			addCriterion("CUADRA like", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraNotLike(String value) {
			addCriterion("CUADRA not like", value, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraIn(List<String> values) {
			addCriterion("CUADRA in", values, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraNotIn(List<String> values) {
			addCriterion("CUADRA not in", values, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraBetween(String value1, String value2) {
			addCriterion("CUADRA between", value1, value2, "cuadra");
			return (Criteria) this;
		}

		public Criteria andCuadraNotBetween(String value1, String value2) {
			addCriterion("CUADRA not between", value1, value2, "cuadra");
			return (Criteria) this;
		}

		public Criteria andMotivoIsNull() {
			addCriterion("MOTIVO is null");
			return (Criteria) this;
		}

		public Criteria andMotivoIsNotNull() {
			addCriterion("MOTIVO is not null");
			return (Criteria) this;
		}

		public Criteria andMotivoEqualTo(String value) {
			addCriterion("MOTIVO =", value, "motivo");
			return (Criteria) this;
		}

		public Criteria andMotivoNotEqualTo(String value) {
			addCriterion("MOTIVO <>", value, "motivo");
			return (Criteria) this;
		}

		public Criteria andMotivoGreaterThan(String value) {
			addCriterion("MOTIVO >", value, "motivo");
			return (Criteria) this;
		}

		public Criteria andMotivoGreaterThanOrEqualTo(String value) {
			addCriterion("MOTIVO >=", value, "motivo");
			return (Criteria) this;
		}

		public Criteria andMotivoLessThan(String value) {
			addCriterion("MOTIVO <", value, "motivo");
			return (Criteria) this;
		}

		public Criteria andMotivoLessThanOrEqualTo(String value) {
			addCriterion("MOTIVO <=", value, "motivo");
			return (Criteria) this;
		}

		public Criteria andMotivoLike(String value) {
			addCriterion("MOTIVO like", value, "motivo");
			return (Criteria) this;
		}

		public Criteria andMotivoNotLike(String value) {
			addCriterion("MOTIVO not like", value, "motivo");
			return (Criteria) this;
		}

		public Criteria andMotivoIn(List<String> values) {
			addCriterion("MOTIVO in", values, "motivo");
			return (Criteria) this;
		}

		public Criteria andMotivoNotIn(List<String> values) {
			addCriterion("MOTIVO not in", values, "motivo");
			return (Criteria) this;
		}

		public Criteria andMotivoBetween(String value1, String value2) {
			addCriterion("MOTIVO between", value1, value2, "motivo");
			return (Criteria) this;
		}

		public Criteria andMotivoNotBetween(String value1, String value2) {
			addCriterion("MOTIVO not between", value1, value2, "motivo");
			return (Criteria) this;
		}

		public Criteria andEmpresaIsNull() {
			addCriterion("EMPRESA is null");
			return (Criteria) this;
		}

		public Criteria andEmpresaIsNotNull() {
			addCriterion("EMPRESA is not null");
			return (Criteria) this;
		}

		public Criteria andEmpresaEqualTo(String value) {
			addCriterion("EMPRESA =", value, "empresa");
			return (Criteria) this;
		}

		public Criteria andEmpresaNotEqualTo(String value) {
			addCriterion("EMPRESA <>", value, "empresa");
			return (Criteria) this;
		}

		public Criteria andEmpresaGreaterThan(String value) {
			addCriterion("EMPRESA >", value, "empresa");
			return (Criteria) this;
		}

		public Criteria andEmpresaGreaterThanOrEqualTo(String value) {
			addCriterion("EMPRESA >=", value, "empresa");
			return (Criteria) this;
		}

		public Criteria andEmpresaLessThan(String value) {
			addCriterion("EMPRESA <", value, "empresa");
			return (Criteria) this;
		}

		public Criteria andEmpresaLessThanOrEqualTo(String value) {
			addCriterion("EMPRESA <=", value, "empresa");
			return (Criteria) this;
		}

		public Criteria andEmpresaLike(String value) {
			addCriterion("EMPRESA like", value, "empresa");
			return (Criteria) this;
		}

		public Criteria andEmpresaNotLike(String value) {
			addCriterion("EMPRESA not like", value, "empresa");
			return (Criteria) this;
		}

		public Criteria andEmpresaIn(List<String> values) {
			addCriterion("EMPRESA in", values, "empresa");
			return (Criteria) this;
		}

		public Criteria andEmpresaNotIn(List<String> values) {
			addCriterion("EMPRESA not in", values, "empresa");
			return (Criteria) this;
		}

		public Criteria andEmpresaBetween(String value1, String value2) {
			addCriterion("EMPRESA between", value1, value2, "empresa");
			return (Criteria) this;
		}

		public Criteria andEmpresaNotBetween(String value1, String value2) {
			addCriterion("EMPRESA not between", value1, value2, "empresa");
			return (Criteria) this;
		}

		public Criteria andIdentGrupoIsNull() {
			addCriterion("IDENT_GRUPO is null");
			return (Criteria) this;
		}

		public Criteria andIdentGrupoIsNotNull() {
			addCriterion("IDENT_GRUPO is not null");
			return (Criteria) this;
		}

		public Criteria andIdentGrupoEqualTo(Integer value) {
			addCriterion("IDENT_GRUPO =", value, "identGrupo");
			return (Criteria) this;
		}

		public Criteria andIdentGrupoNotEqualTo(Integer value) {
			addCriterion("IDENT_GRUPO <>", value, "identGrupo");
			return (Criteria) this;
		}

		public Criteria andIdentGrupoGreaterThan(Integer value) {
			addCriterion("IDENT_GRUPO >", value, "identGrupo");
			return (Criteria) this;
		}

		public Criteria andIdentGrupoGreaterThanOrEqualTo(Integer value) {
			addCriterion("IDENT_GRUPO >=", value, "identGrupo");
			return (Criteria) this;
		}

		public Criteria andIdentGrupoLessThan(Integer value) {
			addCriterion("IDENT_GRUPO <", value, "identGrupo");
			return (Criteria) this;
		}

		public Criteria andIdentGrupoLessThanOrEqualTo(Integer value) {
			addCriterion("IDENT_GRUPO <=", value, "identGrupo");
			return (Criteria) this;
		}

		public Criteria andIdentGrupoIn(List<Integer> values) {
			addCriterion("IDENT_GRUPO in", values, "identGrupo");
			return (Criteria) this;
		}

		public Criteria andIdentGrupoNotIn(List<Integer> values) {
			addCriterion("IDENT_GRUPO not in", values, "identGrupo");
			return (Criteria) this;
		}

		public Criteria andIdentGrupoBetween(Integer value1, Integer value2) {
			addCriterion("IDENT_GRUPO between", value1, value2, "identGrupo");
			return (Criteria) this;
		}

		public Criteria andIdentGrupoNotBetween(Integer value1, Integer value2) {
			addCriterion("IDENT_GRUPO not between", value1, value2, "identGrupo");
			return (Criteria) this;
		}

		public Criteria andEstadoIsNull() {
			addCriterion("ESTADO is null");
			return (Criteria) this;
		}

		public Criteria andEstadoIsNotNull() {
			addCriterion("ESTADO is not null");
			return (Criteria) this;
		}

		public Criteria andEstadoEqualTo(Integer value) {
			addCriterion("ESTADO =", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoNotEqualTo(Integer value) {
			addCriterion("ESTADO <>", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoGreaterThan(Integer value) {
			addCriterion("ESTADO >", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoGreaterThanOrEqualTo(Integer value) {
			addCriterion("ESTADO >=", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoLessThan(Integer value) {
			addCriterion("ESTADO <", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoLessThanOrEqualTo(Integer value) {
			addCriterion("ESTADO <=", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoIn(List<Integer> values) {
			addCriterion("ESTADO in", values, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoNotIn(List<Integer> values) {
			addCriterion("ESTADO not in", values, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoBetween(Integer value1, Integer value2) {
			addCriterion("ESTADO between", value1, value2, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoNotBetween(Integer value1, Integer value2) {
			addCriterion("ESTADO not between", value1, value2, "estado");
			return (Criteria) this;
		}

		public Criteria andFecRegistroIsNull() {
			addCriterion("FEC_REGISTRO is null");
			return (Criteria) this;
		}

		public Criteria andFecRegistroIsNotNull() {
			addCriterion("FEC_REGISTRO is not null");
			return (Criteria) this;
		}

		public Criteria andFecRegistroEqualTo(Date value) {
			addCriterion("FEC_REGISTRO =", value, "fecRegistro");
			return (Criteria) this;
		}

		public Criteria andFecRegistroNotEqualTo(Date value) {
			addCriterion("FEC_REGISTRO <>", value, "fecRegistro");
			return (Criteria) this;
		}

		public Criteria andFecRegistroGreaterThan(Date value) {
			addCriterion("FEC_REGISTRO >", value, "fecRegistro");
			return (Criteria) this;
		}

		public Criteria andFecRegistroGreaterThanOrEqualTo(Date value) {
			addCriterion("FEC_REGISTRO >=", value, "fecRegistro");
			return (Criteria) this;
		}

		public Criteria andFecRegistroLessThan(Date value) {
			addCriterion("FEC_REGISTRO <", value, "fecRegistro");
			return (Criteria) this;
		}

		public Criteria andFecRegistroLessThanOrEqualTo(Date value) {
			addCriterion("FEC_REGISTRO <=", value, "fecRegistro");
			return (Criteria) this;
		}

		public Criteria andFecRegistroIn(List<Date> values) {
			addCriterion("FEC_REGISTRO in", values, "fecRegistro");
			return (Criteria) this;
		}

		public Criteria andFecRegistroNotIn(List<Date> values) {
			addCriterion("FEC_REGISTRO not in", values, "fecRegistro");
			return (Criteria) this;
		}

		public Criteria andFecRegistroBetween(Date value1, Date value2) {
			addCriterion("FEC_REGISTRO between", value1, value2, "fecRegistro");
			return (Criteria) this;
		}

		public Criteria andFecRegistroNotBetween(Date value1, Date value2) {
			addCriterion("FEC_REGISTRO not between", value1, value2, "fecRegistro");
			return (Criteria) this;
		}

		public Criteria andFecModificacionIsNull() {
			addCriterion("FEC_MODIFICACION is null");
			return (Criteria) this;
		}

		public Criteria andFecModificacionIsNotNull() {
			addCriterion("FEC_MODIFICACION is not null");
			return (Criteria) this;
		}

		public Criteria andFecModificacionEqualTo(Date value) {
			addCriterion("FEC_MODIFICACION =", value, "fecModificacion");
			return (Criteria) this;
		}

		public Criteria andFecModificacionNotEqualTo(Date value) {
			addCriterion("FEC_MODIFICACION <>", value, "fecModificacion");
			return (Criteria) this;
		}

		public Criteria andFecModificacionGreaterThan(Date value) {
			addCriterion("FEC_MODIFICACION >", value, "fecModificacion");
			return (Criteria) this;
		}

		public Criteria andFecModificacionGreaterThanOrEqualTo(Date value) {
			addCriterion("FEC_MODIFICACION >=", value, "fecModificacion");
			return (Criteria) this;
		}

		public Criteria andFecModificacionLessThan(Date value) {
			addCriterion("FEC_MODIFICACION <", value, "fecModificacion");
			return (Criteria) this;
		}

		public Criteria andFecModificacionLessThanOrEqualTo(Date value) {
			addCriterion("FEC_MODIFICACION <=", value, "fecModificacion");
			return (Criteria) this;
		}

		public Criteria andFecModificacionIn(List<Date> values) {
			addCriterion("FEC_MODIFICACION in", values, "fecModificacion");
			return (Criteria) this;
		}

		public Criteria andFecModificacionNotIn(List<Date> values) {
			addCriterion("FEC_MODIFICACION not in", values, "fecModificacion");
			return (Criteria) this;
		}

		public Criteria andFecModificacionBetween(Date value1, Date value2) {
			addCriterion("FEC_MODIFICACION between", value1, value2, "fecModificacion");
			return (Criteria) this;
		}

		public Criteria andFecModificacionNotBetween(Date value1, Date value2) {
			addCriterion("FEC_MODIFICACION not between", value1, value2, "fecModificacion");
			return (Criteria) this;
		}

		public Criteria andIpRegistroIsNull() {
			addCriterion("IP_REGISTRO is null");
			return (Criteria) this;
		}

		public Criteria andIpRegistroIsNotNull() {
			addCriterion("IP_REGISTRO is not null");
			return (Criteria) this;
		}

		public Criteria andIpRegistroEqualTo(String value) {
			addCriterion("IP_REGISTRO =", value, "ipRegistro");
			return (Criteria) this;
		}

		public Criteria andIpRegistroNotEqualTo(String value) {
			addCriterion("IP_REGISTRO <>", value, "ipRegistro");
			return (Criteria) this;
		}

		public Criteria andIpRegistroGreaterThan(String value) {
			addCriterion("IP_REGISTRO >", value, "ipRegistro");
			return (Criteria) this;
		}

		public Criteria andIpRegistroGreaterThanOrEqualTo(String value) {
			addCriterion("IP_REGISTRO >=", value, "ipRegistro");
			return (Criteria) this;
		}

		public Criteria andIpRegistroLessThan(String value) {
			addCriterion("IP_REGISTRO <", value, "ipRegistro");
			return (Criteria) this;
		}

		public Criteria andIpRegistroLessThanOrEqualTo(String value) {
			addCriterion("IP_REGISTRO <=", value, "ipRegistro");
			return (Criteria) this;
		}

		public Criteria andIpRegistroLike(String value) {
			addCriterion("IP_REGISTRO like", value, "ipRegistro");
			return (Criteria) this;
		}

		public Criteria andIpRegistroNotLike(String value) {
			addCriterion("IP_REGISTRO not like", value, "ipRegistro");
			return (Criteria) this;
		}

		public Criteria andIpRegistroIn(List<String> values) {
			addCriterion("IP_REGISTRO in", values, "ipRegistro");
			return (Criteria) this;
		}

		public Criteria andIpRegistroNotIn(List<String> values) {
			addCriterion("IP_REGISTRO not in", values, "ipRegistro");
			return (Criteria) this;
		}

		public Criteria andIpRegistroBetween(String value1, String value2) {
			addCriterion("IP_REGISTRO between", value1, value2, "ipRegistro");
			return (Criteria) this;
		}

		public Criteria andIpRegistroNotBetween(String value1, String value2) {
			addCriterion("IP_REGISTRO not between", value1, value2, "ipRegistro");
			return (Criteria) this;
		}

		public Criteria andIpModificacionIsNull() {
			addCriterion("IP_MODIFICACION is null");
			return (Criteria) this;
		}

		public Criteria andIpModificacionIsNotNull() {
			addCriterion("IP_MODIFICACION is not null");
			return (Criteria) this;
		}

		public Criteria andIpModificacionEqualTo(String value) {
			addCriterion("IP_MODIFICACION =", value, "ipModificacion");
			return (Criteria) this;
		}

		public Criteria andIpModificacionNotEqualTo(String value) {
			addCriterion("IP_MODIFICACION <>", value, "ipModificacion");
			return (Criteria) this;
		}

		public Criteria andIpModificacionGreaterThan(String value) {
			addCriterion("IP_MODIFICACION >", value, "ipModificacion");
			return (Criteria) this;
		}

		public Criteria andIpModificacionGreaterThanOrEqualTo(String value) {
			addCriterion("IP_MODIFICACION >=", value, "ipModificacion");
			return (Criteria) this;
		}

		public Criteria andIpModificacionLessThan(String value) {
			addCriterion("IP_MODIFICACION <", value, "ipModificacion");
			return (Criteria) this;
		}

		public Criteria andIpModificacionLessThanOrEqualTo(String value) {
			addCriterion("IP_MODIFICACION <=", value, "ipModificacion");
			return (Criteria) this;
		}

		public Criteria andIpModificacionLike(String value) {
			addCriterion("IP_MODIFICACION like", value, "ipModificacion");
			return (Criteria) this;
		}

		public Criteria andIpModificacionNotLike(String value) {
			addCriterion("IP_MODIFICACION not like", value, "ipModificacion");
			return (Criteria) this;
		}

		public Criteria andIpModificacionIn(List<String> values) {
			addCriterion("IP_MODIFICACION in", values, "ipModificacion");
			return (Criteria) this;
		}

		public Criteria andIpModificacionNotIn(List<String> values) {
			addCriterion("IP_MODIFICACION not in", values, "ipModificacion");
			return (Criteria) this;
		}

		public Criteria andIpModificacionBetween(String value1, String value2) {
			addCriterion("IP_MODIFICACION between", value1, value2, "ipModificacion");
			return (Criteria) this;
		}

		public Criteria andIpModificacionNotBetween(String value1, String value2) {
			addCriterion("IP_MODIFICACION not between", value1, value2, "ipModificacion");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteIsNull() {
			addCriterion("NUM_EXPEDIENTE is null");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteIsNotNull() {
			addCriterion("NUM_EXPEDIENTE is not null");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteEqualTo(String value) {
			addCriterion("NUM_EXPEDIENTE =", value, "numExpediente");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteNotEqualTo(String value) {
			addCriterion("NUM_EXPEDIENTE <>", value, "numExpediente");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteGreaterThan(String value) {
			addCriterion("NUM_EXPEDIENTE >", value, "numExpediente");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteGreaterThanOrEqualTo(String value) {
			addCriterion("NUM_EXPEDIENTE >=", value, "numExpediente");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteLessThan(String value) {
			addCriterion("NUM_EXPEDIENTE <", value, "numExpediente");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteLessThanOrEqualTo(String value) {
			addCriterion("NUM_EXPEDIENTE <=", value, "numExpediente");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteLike(String value) {
			addCriterion("NUM_EXPEDIENTE like", value, "numExpediente");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteNotLike(String value) {
			addCriterion("NUM_EXPEDIENTE not like", value, "numExpediente");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteIn(List<String> values) {
			addCriterion("NUM_EXPEDIENTE in", values, "numExpediente");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteNotIn(List<String> values) {
			addCriterion("NUM_EXPEDIENTE not in", values, "numExpediente");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteBetween(String value1, String value2) {
			addCriterion("NUM_EXPEDIENTE between", value1, value2, "numExpediente");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteNotBetween(String value1, String value2) {
			addCriterion("NUM_EXPEDIENTE not between", value1, value2, "numExpediente");
			return (Criteria) this;
		}

		public Criteria andAnioExpedienteIsNull() {
			addCriterion("ANIO_EXPEDIENTE is null");
			return (Criteria) this;
		}

		public Criteria andAnioExpedienteIsNotNull() {
			addCriterion("ANIO_EXPEDIENTE is not null");
			return (Criteria) this;
		}

		public Criteria andAnioExpedienteEqualTo(Integer value) {
			addCriterion("ANIO_EXPEDIENTE =", value, "anioExpediente");
			return (Criteria) this;
		}

		public Criteria andAnioExpedienteNotEqualTo(Integer value) {
			addCriterion("ANIO_EXPEDIENTE <>", value, "anioExpediente");
			return (Criteria) this;
		}

		public Criteria andAnioExpedienteGreaterThan(Integer value) {
			addCriterion("ANIO_EXPEDIENTE >", value, "anioExpediente");
			return (Criteria) this;
		}

		public Criteria andAnioExpedienteGreaterThanOrEqualTo(Integer value) {
			addCriterion("ANIO_EXPEDIENTE >=", value, "anioExpediente");
			return (Criteria) this;
		}

		public Criteria andAnioExpedienteLessThan(Integer value) {
			addCriterion("ANIO_EXPEDIENTE <", value, "anioExpediente");
			return (Criteria) this;
		}

		public Criteria andAnioExpedienteLessThanOrEqualTo(Integer value) {
			addCriterion("ANIO_EXPEDIENTE <=", value, "anioExpediente");
			return (Criteria) this;
		}

		public Criteria andAnioExpedienteIn(List<Integer> values) {
			addCriterion("ANIO_EXPEDIENTE in", values, "anioExpediente");
			return (Criteria) this;
		}

		public Criteria andAnioExpedienteNotIn(List<Integer> values) {
			addCriterion("ANIO_EXPEDIENTE not in", values, "anioExpediente");
			return (Criteria) this;
		}

		public Criteria andAnioExpedienteBetween(Integer value1, Integer value2) {
			addCriterion("ANIO_EXPEDIENTE between", value1, value2, "anioExpediente");
			return (Criteria) this;
		}

		public Criteria andAnioExpedienteNotBetween(Integer value1, Integer value2) {
			addCriterion("ANIO_EXPEDIENTE not between", value1, value2, "anioExpediente");
			return (Criteria) this;
		}

		public Criteria andIdReferenciaIsNull() {
			addCriterion("ID_REFERENCIA is null");
			return (Criteria) this;
		}

		public Criteria andIdReferenciaIsNotNull() {
			addCriterion("ID_REFERENCIA is not null");
			return (Criteria) this;
		}

		public Criteria andIdReferenciaEqualTo(Integer value) {
			addCriterion("ID_REFERENCIA =", value, "idReferencia");
			return (Criteria) this;
		}

		public Criteria andIdReferenciaNotEqualTo(Integer value) {
			addCriterion("ID_REFERENCIA <>", value, "idReferencia");
			return (Criteria) this;
		}

		public Criteria andIdReferenciaGreaterThan(Integer value) {
			addCriterion("ID_REFERENCIA >", value, "idReferencia");
			return (Criteria) this;
		}

		public Criteria andIdReferenciaGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID_REFERENCIA >=", value, "idReferencia");
			return (Criteria) this;
		}

		public Criteria andIdReferenciaLessThan(Integer value) {
			addCriterion("ID_REFERENCIA <", value, "idReferencia");
			return (Criteria) this;
		}

		public Criteria andIdReferenciaLessThanOrEqualTo(Integer value) {
			addCriterion("ID_REFERENCIA <=", value, "idReferencia");
			return (Criteria) this;
		}

		public Criteria andIdReferenciaIn(List<Integer> values) {
			addCriterion("ID_REFERENCIA in", values, "idReferencia");
			return (Criteria) this;
		}

		public Criteria andIdReferenciaNotIn(List<Integer> values) {
			addCriterion("ID_REFERENCIA not in", values, "idReferencia");
			return (Criteria) this;
		}

		public Criteria andIdReferenciaBetween(Integer value1, Integer value2) {
			addCriterion("ID_REFERENCIA between", value1, value2, "idReferencia");
			return (Criteria) this;
		}

		public Criteria andIdReferenciaNotBetween(Integer value1, Integer value2) {
			addCriterion("ID_REFERENCIA not between", value1, value2, "idReferencia");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionIsNull() {
			addCriterion("MAS_UNA_DIRECCION is null");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionIsNotNull() {
			addCriterion("MAS_UNA_DIRECCION is not null");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionEqualTo(String value) {
			addCriterion("MAS_UNA_DIRECCION =", value, "masUnaDireccion");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionNotEqualTo(String value) {
			addCriterion("MAS_UNA_DIRECCION <>", value, "masUnaDireccion");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionGreaterThan(String value) {
			addCriterion("MAS_UNA_DIRECCION >", value, "masUnaDireccion");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionGreaterThanOrEqualTo(String value) {
			addCriterion("MAS_UNA_DIRECCION >=", value, "masUnaDireccion");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionLessThan(String value) {
			addCriterion("MAS_UNA_DIRECCION <", value, "masUnaDireccion");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionLessThanOrEqualTo(String value) {
			addCriterion("MAS_UNA_DIRECCION <=", value, "masUnaDireccion");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionLike(String value) {
			addCriterion("MAS_UNA_DIRECCION like", value, "masUnaDireccion");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionNotLike(String value) {
			addCriterion("MAS_UNA_DIRECCION not like", value, "masUnaDireccion");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionIn(List<String> values) {
			addCriterion("MAS_UNA_DIRECCION in", values, "masUnaDireccion");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionNotIn(List<String> values) {
			addCriterion("MAS_UNA_DIRECCION not in", values, "masUnaDireccion");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionBetween(String value1, String value2) {
			addCriterion("MAS_UNA_DIRECCION between", value1, value2, "masUnaDireccion");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionNotBetween(String value1, String value2) {
			addCriterion("MAS_UNA_DIRECCION not between", value1, value2, "masUnaDireccion");
			return (Criteria) this;
		}

		public Criteria andGidIsNull() {
			addCriterion("GID is null");
			return (Criteria) this;
		}

		public Criteria andGidIsNotNull() {
			addCriterion("GID is not null");
			return (Criteria) this;
		}

		public Criteria andGidEqualTo(Integer value) {
			addCriterion("GID =", value, "gid");
			return (Criteria) this;
		}

		public Criteria andGidNotEqualTo(Integer value) {
			addCriterion("GID <>", value, "gid");
			return (Criteria) this;
		}

		public Criteria andGidGreaterThan(Integer value) {
			addCriterion("GID >", value, "gid");
			return (Criteria) this;
		}

		public Criteria andGidGreaterThanOrEqualTo(Integer value) {
			addCriterion("GID >=", value, "gid");
			return (Criteria) this;
		}

		public Criteria andGidLessThan(Integer value) {
			addCriterion("GID <", value, "gid");
			return (Criteria) this;
		}

		public Criteria andGidLessThanOrEqualTo(Integer value) {
			addCriterion("GID <=", value, "gid");
			return (Criteria) this;
		}

		public Criteria andGidIn(List<Integer> values) {
			addCriterion("GID in", values, "gid");
			return (Criteria) this;
		}

		public Criteria andGidNotIn(List<Integer> values) {
			addCriterion("GID not in", values, "gid");
			return (Criteria) this;
		}

		public Criteria andGidBetween(Integer value1, Integer value2) {
			addCriterion("GID between", value1, value2, "gid");
			return (Criteria) this;
		}

		public Criteria andGidNotBetween(Integer value1, Integer value2) {
			addCriterion("GID not between", value1, value2, "gid");
			return (Criteria) this;
		}

		public Criteria andDireccionLikeInsensitive(String value) {
			addCriterion("upper(DIRECCION) like", value.toUpperCase(), "direccion");
			return (Criteria) this;
		}

		public Criteria andCuadraLikeInsensitive(String value) {
			addCriterion("upper(CUADRA) like", value.toUpperCase(), "cuadra");
			return (Criteria) this;
		}

		public Criteria andMotivoLikeInsensitive(String value) {
			addCriterion("upper(MOTIVO) like", value.toUpperCase(), "motivo");
			return (Criteria) this;
		}

		public Criteria andEmpresaLikeInsensitive(String value) {
			addCriterion("upper(EMPRESA) like", value.toUpperCase(), "empresa");
			return (Criteria) this;
		}

		public Criteria andIpRegistroLikeInsensitive(String value) {
			addCriterion("upper(IP_REGISTRO) like", value.toUpperCase(), "ipRegistro");
			return (Criteria) this;
		}

		public Criteria andIpModificacionLikeInsensitive(String value) {
			addCriterion("upper(IP_MODIFICACION) like", value.toUpperCase(), "ipModificacion");
			return (Criteria) this;
		}

		public Criteria andNumExpedienteLikeInsensitive(String value) {
			addCriterion("upper(NUM_EXPEDIENTE) like", value.toUpperCase(), "numExpediente");
			return (Criteria) this;
		}

		public Criteria andMasUnaDireccionLikeInsensitive(String value) {
			addCriterion("upper(MAS_UNA_DIRECCION) like", value.toUpperCase(), "masUnaDireccion");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
     *
     * @mbggenerated do_not_delete_during_merge Mon May 09 15:43:15 COT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}