package pe.gob.miraflores.mobile.domain.mapaincidencias;

import java.util.Date;

public class PreInscripcionCierreCalle {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.ID
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.DIRECCION
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private String direccion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.CUADRA
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private String cuadra;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.MOTIVO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private String motivo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.EMPRESA
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private String empresa;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.IDENT_GRUPO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private Integer identGrupo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.ESTADO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private Integer estado;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.FEC_REGISTRO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private Date fecRegistro;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.FEC_MODIFICACION
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private Date fecModificacion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.IP_REGISTRO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private String ipRegistro;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.IP_MODIFICACION
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private String ipModificacion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.NUM_EXPEDIENTE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private String numExpediente;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.ANIO_EXPEDIENTE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private Integer anioExpediente;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.ID_REFERENCIA
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private Integer idReferencia;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.MAS_UNA_DIRECCION
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private String masUnaDireccion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRE_INSCRIPCION_CIERRE_CALLE.GID
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	private Integer gid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.ID
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.ID
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.ID
	 * @param id  the value for PRE_INSCRIPCION_CIERRE_CALLE.ID
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.DIRECCION
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.DIRECCION
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public String getDireccion() {
		return direccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.DIRECCION
	 * @param direccion  the value for PRE_INSCRIPCION_CIERRE_CALLE.DIRECCION
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.CUADRA
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.CUADRA
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public String getCuadra() {
		return cuadra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.CUADRA
	 * @param cuadra  the value for PRE_INSCRIPCION_CIERRE_CALLE.CUADRA
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setCuadra(String cuadra) {
		this.cuadra = cuadra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.MOTIVO
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.MOTIVO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public String getMotivo() {
		return motivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.MOTIVO
	 * @param motivo  the value for PRE_INSCRIPCION_CIERRE_CALLE.MOTIVO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.EMPRESA
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.EMPRESA
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public String getEmpresa() {
		return empresa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.EMPRESA
	 * @param empresa  the value for PRE_INSCRIPCION_CIERRE_CALLE.EMPRESA
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.IDENT_GRUPO
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.IDENT_GRUPO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public Integer getIdentGrupo() {
		return identGrupo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.IDENT_GRUPO
	 * @param identGrupo  the value for PRE_INSCRIPCION_CIERRE_CALLE.IDENT_GRUPO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setIdentGrupo(Integer identGrupo) {
		this.identGrupo = identGrupo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.ESTADO
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.ESTADO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public Integer getEstado() {
		return estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.ESTADO
	 * @param estado  the value for PRE_INSCRIPCION_CIERRE_CALLE.ESTADO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.FEC_REGISTRO
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.FEC_REGISTRO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public Date getFecRegistro() {
		return fecRegistro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.FEC_REGISTRO
	 * @param fecRegistro  the value for PRE_INSCRIPCION_CIERRE_CALLE.FEC_REGISTRO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setFecRegistro(Date fecRegistro) {
		this.fecRegistro = fecRegistro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.FEC_MODIFICACION
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.FEC_MODIFICACION
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public Date getFecModificacion() {
		return fecModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.FEC_MODIFICACION
	 * @param fecModificacion  the value for PRE_INSCRIPCION_CIERRE_CALLE.FEC_MODIFICACION
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setFecModificacion(Date fecModificacion) {
		this.fecModificacion = fecModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.IP_REGISTRO
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.IP_REGISTRO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public String getIpRegistro() {
		return ipRegistro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.IP_REGISTRO
	 * @param ipRegistro  the value for PRE_INSCRIPCION_CIERRE_CALLE.IP_REGISTRO
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setIpRegistro(String ipRegistro) {
		this.ipRegistro = ipRegistro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.IP_MODIFICACION
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.IP_MODIFICACION
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public String getIpModificacion() {
		return ipModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.IP_MODIFICACION
	 * @param ipModificacion  the value for PRE_INSCRIPCION_CIERRE_CALLE.IP_MODIFICACION
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.NUM_EXPEDIENTE
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.NUM_EXPEDIENTE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public String getNumExpediente() {
		return numExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.NUM_EXPEDIENTE
	 * @param numExpediente  the value for PRE_INSCRIPCION_CIERRE_CALLE.NUM_EXPEDIENTE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setNumExpediente(String numExpediente) {
		this.numExpediente = numExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.ANIO_EXPEDIENTE
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.ANIO_EXPEDIENTE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public Integer getAnioExpediente() {
		return anioExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.ANIO_EXPEDIENTE
	 * @param anioExpediente  the value for PRE_INSCRIPCION_CIERRE_CALLE.ANIO_EXPEDIENTE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setAnioExpediente(Integer anioExpediente) {
		this.anioExpediente = anioExpediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.ID_REFERENCIA
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.ID_REFERENCIA
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public Integer getIdReferencia() {
		return idReferencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.ID_REFERENCIA
	 * @param idReferencia  the value for PRE_INSCRIPCION_CIERRE_CALLE.ID_REFERENCIA
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setIdReferencia(Integer idReferencia) {
		this.idReferencia = idReferencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.MAS_UNA_DIRECCION
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.MAS_UNA_DIRECCION
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public String getMasUnaDireccion() {
		return masUnaDireccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.MAS_UNA_DIRECCION
	 * @param masUnaDireccion  the value for PRE_INSCRIPCION_CIERRE_CALLE.MAS_UNA_DIRECCION
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setMasUnaDireccion(String masUnaDireccion) {
		this.masUnaDireccion = masUnaDireccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.GID
	 * @return  the value of PRE_INSCRIPCION_CIERRE_CALLE.GID
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public Integer getGid() {
		return gid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRE_INSCRIPCION_CIERRE_CALLE.GID
	 * @param gid  the value for PRE_INSCRIPCION_CIERRE_CALLE.GID
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	public void setGid(Integer gid) {
		this.gid = gid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		PreInscripcionCierreCalle other = (PreInscripcionCierreCalle) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getDireccion() == null ? other.getDireccion() == null
						: this.getDireccion().equals(other.getDireccion()))
				&& (this.getCuadra() == null ? other.getCuadra() == null : this.getCuadra().equals(other.getCuadra()))
				&& (this.getMotivo() == null ? other.getMotivo() == null : this.getMotivo().equals(other.getMotivo()))
				&& (this.getEmpresa() == null ? other.getEmpresa() == null
						: this.getEmpresa().equals(other.getEmpresa()))
				&& (this.getIdentGrupo() == null ? other.getIdentGrupo() == null
						: this.getIdentGrupo().equals(other.getIdentGrupo()))
				&& (this.getEstado() == null ? other.getEstado() == null : this.getEstado().equals(other.getEstado()))
				&& (this.getFecRegistro() == null ? other.getFecRegistro() == null
						: this.getFecRegistro().equals(other.getFecRegistro()))
				&& (this.getFecModificacion() == null ? other.getFecModificacion() == null
						: this.getFecModificacion().equals(other.getFecModificacion()))
				&& (this.getIpRegistro() == null ? other.getIpRegistro() == null
						: this.getIpRegistro().equals(other.getIpRegistro()))
				&& (this.getIpModificacion() == null ? other.getIpModificacion() == null
						: this.getIpModificacion().equals(other.getIpModificacion()))
				&& (this.getNumExpediente() == null ? other.getNumExpediente() == null
						: this.getNumExpediente().equals(other.getNumExpediente()))
				&& (this.getAnioExpediente() == null ? other.getAnioExpediente() == null
						: this.getAnioExpediente().equals(other.getAnioExpediente()))
				&& (this.getIdReferencia() == null ? other.getIdReferencia() == null
						: this.getIdReferencia().equals(other.getIdReferencia()))
				&& (this.getMasUnaDireccion() == null ? other.getMasUnaDireccion() == null
						: this.getMasUnaDireccion().equals(other.getMasUnaDireccion()))
				&& (this.getGid() == null ? other.getGid() == null : this.getGid().equals(other.getGid()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getDireccion() == null) ? 0 : getDireccion().hashCode());
		result = prime * result + ((getCuadra() == null) ? 0 : getCuadra().hashCode());
		result = prime * result + ((getMotivo() == null) ? 0 : getMotivo().hashCode());
		result = prime * result + ((getEmpresa() == null) ? 0 : getEmpresa().hashCode());
		result = prime * result + ((getIdentGrupo() == null) ? 0 : getIdentGrupo().hashCode());
		result = prime * result + ((getEstado() == null) ? 0 : getEstado().hashCode());
		result = prime * result + ((getFecRegistro() == null) ? 0 : getFecRegistro().hashCode());
		result = prime * result + ((getFecModificacion() == null) ? 0 : getFecModificacion().hashCode());
		result = prime * result + ((getIpRegistro() == null) ? 0 : getIpRegistro().hashCode());
		result = prime * result + ((getIpModificacion() == null) ? 0 : getIpModificacion().hashCode());
		result = prime * result + ((getNumExpediente() == null) ? 0 : getNumExpediente().hashCode());
		result = prime * result + ((getAnioExpediente() == null) ? 0 : getAnioExpediente().hashCode());
		result = prime * result + ((getIdReferencia() == null) ? 0 : getIdReferencia().hashCode());
		result = prime * result + ((getMasUnaDireccion() == null) ? 0 : getMasUnaDireccion().hashCode());
		result = prime * result + ((getGid() == null) ? 0 : getGid().hashCode());
		return result;
	}

	private String direccionIP;
    
    private String desUsuario;

	public String getDireccionIP() {
		return direccionIP;
	}

	public void setDireccionIP(String direccionIP) {
		this.direccionIP = direccionIP;
	}

	public String getDesUsuario() {
		return desUsuario;
	}

	public void setDesUsuario(String desUsuario) {
		this.desUsuario = desUsuario;
	}
    
}