package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.AuditoriaIncidencia;
import pe.gob.miraflores.mobile.domain.mapaincidencias.AuditoriaIncidenciaCriteria;

public interface AuditoriaIncidenciaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_AUDITORIA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    int countByExample(AuditoriaIncidenciaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_AUDITORIA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    int deleteByExample(AuditoriaIncidenciaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_AUDITORIA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_AUDITORIA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    int insert(AuditoriaIncidencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_AUDITORIA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    int insertSelective(AuditoriaIncidencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_AUDITORIA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    List<AuditoriaIncidencia> selectByExample(AuditoriaIncidenciaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_AUDITORIA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    AuditoriaIncidencia selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_AUDITORIA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    int updateByExampleSelective(@Param("record") AuditoriaIncidencia record, @Param("example") AuditoriaIncidenciaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_AUDITORIA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    int updateByExample(@Param("record") AuditoriaIncidencia record, @Param("example") AuditoriaIncidenciaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_AUDITORIA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    int updateByPrimaryKeySelective(AuditoriaIncidencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_AUDITORIA
     *
     * @mbggenerated Wed Sep 21 12:02:13 COT 2016
     */
    int updateByPrimaryKey(AuditoriaIncidencia record);
}