package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciaGenerico;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciaGenericoCriteria;

public interface MapaIncidenciaGenericoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	int countByExample(MapaIncidenciaGenericoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	int deleteByExample(MapaIncidenciaGenericoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	int insert(MapaIncidenciaGenerico record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	int insertSelective(MapaIncidenciaGenerico record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	List<MapaIncidenciaGenerico> selectByExample(MapaIncidenciaGenericoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	MapaIncidenciaGenerico selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	int updateByExampleSelective(@Param("record") MapaIncidenciaGenerico record,
			@Param("example") MapaIncidenciaGenericoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	int updateByExample(@Param("record") MapaIncidenciaGenerico record,
			@Param("example") MapaIncidenciaGenericoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	int updateByPrimaryKeySelective(MapaIncidenciaGenerico record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GEO_MAP_GENERICO
	 * @mbggenerated  Thu Apr 28 17:16:20 COT 2016
	 */
	int updateByPrimaryKey(MapaIncidenciaGenerico record);
}