package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciaSchedule;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciaScheduleCriteria;

public interface MapaIncidenciaScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    int countByExample(MapaIncidenciaScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    int deleteByExample(MapaIncidenciaScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    int insert(MapaIncidenciaSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    int insertSelective(MapaIncidenciaSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    List<MapaIncidenciaSchedule> selectByExample(MapaIncidenciaScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    MapaIncidenciaSchedule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    int updateByExampleSelective(@Param("record") MapaIncidenciaSchedule record, @Param("example") MapaIncidenciaScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    int updateByExample(@Param("record") MapaIncidenciaSchedule record, @Param("example") MapaIncidenciaScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    int updateByPrimaryKeySelective(MapaIncidenciaSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GEO_MAP_INICIDENCIA_SCHEDULE
     *
     * @mbggenerated Tue Sep 06 12:22:00 COT 2016
     */
    int updateByPrimaryKey(MapaIncidenciaSchedule record);
}