package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.mapaincidencias.PreInscripcionCierreCalle;
import pe.gob.miraflores.mobile.domain.mapaincidencias.PreInscripcionCierreCalleCriteria;

public interface PreInscripcionCierreCalleMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	int countByExample(PreInscripcionCierreCalleCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	int deleteByExample(PreInscripcionCierreCalleCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	int insert(PreInscripcionCierreCalle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	int insertSelective(PreInscripcionCierreCalle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	List<PreInscripcionCierreCalle> selectByExample(PreInscripcionCierreCalleCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	PreInscripcionCierreCalle selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	int updateByExampleSelective(@Param("record") PreInscripcionCierreCalle record,
			@Param("example") PreInscripcionCierreCalleCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	int updateByExample(@Param("record") PreInscripcionCierreCalle record,
			@Param("example") PreInscripcionCierreCalleCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	int updateByPrimaryKeySelective(PreInscripcionCierreCalle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRE_INSCRIPCION_CIERRE_CALLE
	 * @mbggenerated  Thu May 19 11:58:41 COT 2016
	 */
	int updateByPrimaryKey(PreInscripcionCierreCalle record);

	public List<PreInscripcionCierreCalle> bandejaPreRegistroCierreCalle(Map<String, Object> params);
    
    
}