package pe.gob.miraflores.mobile.service.mapaincidenciasws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2016-08-19T14:49:06.689-05:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://mapaincidenciasws.service.mobile.miraflores.gob.pe/", name = "MapaIncidenciaWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface MapaIncidenciaWebService {

    @WebMethod
    @RequestWrapper(localName = "createIncidenciaVoxiva", targetNamespace = "http://mapaincidenciasws.service.mobile.miraflores.gob.pe/", className = "pe.gob.miraflores.mobile.service.mapaincidenciasws.CreateIncidenciaVoxiva")
    @ResponseWrapper(localName = "createIncidenciaVoxivaResponse", targetNamespace = "http://mapaincidenciasws.service.mobile.miraflores.gob.pe/", className = "pe.gob.miraflores.mobile.service.mapaincidenciasws.CreateIncidenciaVoxivaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public pe.gob.miraflores.mobile.service.mapaincidenciasws.MessageResult createIncidenciaVoxiva(
        @WebParam(name = "incidencia", targetNamespace = "")
        pe.gob.miraflores.mobile.service.mapaincidenciasws.IncidenciaVoxiva incidencia
    );

    @WebMethod
    @RequestWrapper(localName = "createIncidenciaInfoCambista", targetNamespace = "http://mapaincidenciasws.service.mobile.miraflores.gob.pe/", className = "pe.gob.miraflores.mobile.service.mapaincidenciasws.CreateIncidenciaInfoCambista")
    @ResponseWrapper(localName = "createIncidenciaInfoCambistaResponse", targetNamespace = "http://mapaincidenciasws.service.mobile.miraflores.gob.pe/", className = "pe.gob.miraflores.mobile.service.mapaincidenciasws.CreateIncidenciaInfoCambistaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public pe.gob.miraflores.mobile.service.mapaincidenciasws.MessageResult createIncidenciaInfoCambista(
        @WebParam(name = "record", targetNamespace = "")
        pe.gob.miraflores.mobile.service.mapaincidenciasws.IncidenciaCambista record
    );
}
